// Copyright 2025 Nym Technologies SA <contact@nymtech.net>
// SPDX-License-Identifier: GPL-3.0-only

//! OpenWrt dnsmasq DNS backend. dnsmasq's `resolvfile` is repointed (staged
//! uci, never committed, so a reboot reverts it) at a daemon-managed file
//! in `/tmp/resolv.conf.d/`, which the jailed dnsmasq sees through the init
//! script's bind-mount and reloads via inotify on rename-in. Connect and
//! disconnect are then file writes, not a 3s LAN-wide dnsmasq restart.
//!
//! One daemon-lifetime actor owns the file: tunnel resolvers while
//! connected, a 5s mirror of netifd's `resolv.conf.auto` while idle. Every
//! writer goes through it, so a stale mirror write can never clobber tunnel
//! resolvers. Repointing `resolvfile` also makes the init script write
//! `/tmp/resolv.conf` as 127.0.0.1; `/etc/resolv.conf` is never touched.
//!
//! A committed `noresolv` (AdGuard Home, https-dns-proxy, stubby) makes the
//! init script omit `resolv-file=` entirely; converge then steps aside
//! (`Scheme::UserManaged`) and `set_dns` degrades to a cache flush.

use std::{
    fs, io,
    net::IpAddr,
    path::{Path, PathBuf},
    process::Command,
    sync::OnceLock,
    time::Duration,
};

use tokio::sync::{mpsc, oneshot};

use crate::IdleDns;

pub type Result<T> = std::result::Result<T, Error>;

/// IPv6 upstreams are unreachable unless the exit carries IPv6, which cannot
/// be verified here, and each unreachable one costs a per-lookup timeout.
fn prefer_ipv4_upstreams(servers: &[std::net::IpAddr]) -> Vec<std::net::IpAddr> {
    let v4: Vec<std::net::IpAddr> = servers.iter().copied().filter(|ip| ip.is_ipv4()).collect();
    if v4.is_empty() { servers.to_vec() } else { v4 }
}

const OPENWRT_RELEASE: &str = "/etc/openwrt_release";
const BACKUP_MARKER: &str = "/tmp/nym-dns-backup";
const RESOLV_CONF: &str = "/etc/resolv.conf";
const RESOLV_CONF_BACKUP: &str = "/tmp/resolv.conf.nymbackup";

/// Must live inside /tmp/resolv.conf.d/: the init script bind-mounts
/// dirname(resolvfile) into the ujail. Always a regular file, never a
/// symlink: dnsmasq's inotify resolves the watch name once at startup.
const MANAGED_FILE: &str = "/tmp/resolv.conf.d/nym-resolv.conf";
/// Basename must differ from MANAGED_FILE's; dnsmasq watches by name.
const MANAGED_TMP: &str = "/tmp/resolv.conf.d/.nym-resolv.tmp";
/// netifd-owned WAN resolv file.
const WAN_RESOLV: &str = "/tmp/resolv.conf.d/resolv.conf.auto";

fn render_resolv_conf(servers: &[IpAddr]) -> String {
    let mut out = String::from("# Generated by nym-vpnd\n");
    for server in servers {
        out.push_str(&format!("nameserver {}\n", server));
    }
    out
}

fn generated_conf_points_at(conf: &str, managed_path: &str) -> bool {
    conf.lines()
        .any(|line| line.trim() == format!("resolv-file={}", managed_path))
}

fn committed_has_managed_path(committed_dhcp: &str) -> bool {
    committed_dhcp.contains("nym-resolv.conf")
}

/// First uci section id of type dnsmasq from `uci -X show dhcp` output.
fn parse_dnsmasq_section(uci_show: &str) -> Option<String> {
    uci_show.lines().find_map(|line| {
        let (key, value) = line.split_once('=')?;
        if value == "dnsmasq" {
            key.strip_prefix("dhcp.").map(str::to_owned)
        } else {
            None
        }
    })
}

/// procd reports the ujail wrapper's pid, which forwards SIGHUP. Never read
/// the dnsmasq pidfile: it holds the pid as seen inside the jail ("1").
fn extract_instance_pid(service_json: &str, section: &str) -> Option<u32> {
    let inst = service_json.find(&format!("\"{}\"", section))?;
    let rest = &service_json[inst..];
    let pid_key = rest.find("\"pid\"")?;
    let after = &rest[pid_key + 5..];
    let digits: String = after
        .chars()
        .skip_while(|c| !c.is_ascii_digit())
        .take_while(|c| c.is_ascii_digit())
        .collect();
    digits.parse().ok()
}

/// System interaction boundary, mockable for tests.
trait Sys: Send + Sync + 'static {
    fn uci_revert_option(&self, key: &str);
    /// Staged only, never committed.
    fn uci_set(&self, key: &str, value: &str) -> Result<()>;
    /// The one allowed commit: delete an accidentally-committed resolvfile.
    fn repair_committed_resolvfile(&self) -> Result<()>;
    fn committed_dhcp(&self) -> String;
    /// Must be read after the targeted reverts, or a stale staged delta of
    /// our own could masquerade as user intent.
    fn effective_noresolv(&self, section: &str) -> bool;
    fn dnsmasq_section(&self) -> Option<String>;
    /// Contents of the generated /var/etc/dnsmasq.conf.<section>.
    fn generated_conf(&self, section: &str) -> Option<String>;
    fn restart_dnsmasq(&self) -> Result<()>;
    fn service_json(&self) -> String;
    /// Cache flush only: dnsmasq does not re-read resolv files on SIGHUP;
    /// reload is carried by inotify.
    fn send_hup(&self, pid: u32);
}

impl<T: Sys> Sys for std::sync::Arc<T> {
    fn uci_revert_option(&self, key: &str) {
        (**self).uci_revert_option(key)
    }
    fn uci_set(&self, key: &str, value: &str) -> Result<()> {
        (**self).uci_set(key, value)
    }
    fn repair_committed_resolvfile(&self) -> Result<()> {
        (**self).repair_committed_resolvfile()
    }
    fn committed_dhcp(&self) -> String {
        (**self).committed_dhcp()
    }
    fn effective_noresolv(&self, section: &str) -> bool {
        (**self).effective_noresolv(section)
    }
    fn dnsmasq_section(&self) -> Option<String> {
        (**self).dnsmasq_section()
    }
    fn generated_conf(&self, section: &str) -> Option<String> {
        (**self).generated_conf(section)
    }
    fn restart_dnsmasq(&self) -> Result<()> {
        (**self).restart_dnsmasq()
    }
    fn service_json(&self) -> String {
        (**self).service_json()
    }
    fn send_hup(&self, pid: u32) {
        (**self).send_hup(pid)
    }
}

struct RealSys;

impl Sys for RealSys {
    fn uci_revert_option(&self, key: &str) {
        let output = Command::new("uci").args(["revert", key]).output();
        if let Err(e) = output {
            tracing::warn!("uci revert {} failed to execute: {}", key, e);
        }
    }

    fn uci_set(&self, key: &str, value: &str) -> Result<()> {
        uci_set(key, value)
    }

    fn repair_committed_resolvfile(&self) -> Result<()> {
        let run = |args: &[&str]| -> Result<()> {
            let output = Command::new("uci")
                .args(args)
                .output()
                .map_err(|e| Error::UciCommand(e.to_string()))?;
            if !output.status.success() {
                let stderr = String::from_utf8_lossy(&output.stderr);
                return Err(Error::UciCommand(format!("uci {:?} failed: {}", args, stderr)));
            }
            Ok(())
        };
        run(&["delete", "dhcp.@dnsmasq[0].resolvfile"])?;
        run(&["commit", "dhcp"])
    }

    fn committed_dhcp(&self) -> String {
        fs::read_to_string("/etc/config/dhcp").unwrap_or_default()
    }

    fn effective_noresolv(&self, section: &str) -> bool {
        let output = Command::new("uci")
            .args(["get", &format!("dhcp.{}.noresolv", section)])
            .output();
        let Ok(output) = output else { return false };
        if !output.status.success() {
            return false;
        }
        // config_get_bool's truthy set.
        matches!(
            String::from_utf8_lossy(&output.stdout).trim(),
            "1" | "on" | "true" | "yes" | "enabled"
        )
    }

    fn dnsmasq_section(&self) -> Option<String> {
        // -X gives raw section ids; procd keys its instances by those.
        let output = Command::new("uci").args(["-X", "show", "dhcp"]).output().ok()?;
        parse_dnsmasq_section(&String::from_utf8_lossy(&output.stdout))
    }

    fn generated_conf(&self, section: &str) -> Option<String> {
        fs::read_to_string(format!("/var/etc/dnsmasq.conf.{}", section)).ok()
    }

    fn restart_dnsmasq(&self) -> Result<()> {
        restart_dnsmasq()
    }

    fn service_json(&self) -> String {
        Command::new("ubus")
            .args(["call", "service", "list", r#"{"name":"dnsmasq"}"#])
            .output()
            .map(|o| String::from_utf8_lossy(&o.stdout).into_owned())
            .unwrap_or_default()
    }

    fn send_hup(&self, pid: u32) {
        // BusyBox kill; avoids a libc dependency for one signal.
        let result = Command::new("kill").args(["-HUP", &pid.to_string()]).output();
        match result {
            Ok(o) if o.status.success() => {}
            Ok(o) => tracing::warn!(
                "kill -HUP {} failed: {}",
                pid,
                String::from_utf8_lossy(&o.stderr)
            ),
            Err(e) => tracing::warn!("kill -HUP {} failed to execute: {}", pid, e),
        }
    }
}

enum ConvergeOutcome {
    Ready,
    /// Repoint staged; dnsmasq is left stopped and picks it up on start.
    DnsmasqStopped,
    /// Committed `noresolv`: the init script never emits `resolv-file=`, so
    /// the repoint cannot work. Leave dnsmasq alone.
    UserManagedDns,
}

/// Cached for the actor's lifetime; re-checked on connect by the self-heal paths.
#[derive(Clone, Copy, PartialEq)]
enum Scheme {
    ManagedFile,
    UserManaged,
}

/// Whether the DNS servers configured in nym-vpnd actually reach the system
/// resolver, so the UI can stop claiming a custom-DNS setting is in effect.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UpstreamOwner {
    Vpn,
    /// Committed `noresolv`; dnsmasq's own `server=` forwards resolve.
    User,
    NotApplicable,
}

/// Read-only and not cached off `Scheme`: a user who just edited dhcp sees
/// the truth. Must never converge, stage uci or restart anything.
fn upstream_owner<S: Sys>(sys: &S) -> UpstreamOwner {
    match sys.dnsmasq_section() {
        None => UpstreamOwner::NotApplicable,
        Some(section) if sys.effective_noresolv(&section) => UpstreamOwner::User,
        Some(_) => UpstreamOwner::Vpn,
    }
}

pub fn current_upstream_owner() -> UpstreamOwner {
    if !Path::new(OPENWRT_RELEASE).exists() {
        return UpstreamOwner::NotApplicable;
    }
    upstream_owner(&RealSys)
}

/// Idempotent and run on every daemon start: dnsmasq is restarted only when
/// its generated config does not already point at the managed file, so a
/// crash loop cannot become a restart storm. Also the crash-recovery path.
fn converge<S: Sys>(sys: &S, managed_file: &str) -> Result<ConvergeOutcome> {
    // Targeted reverts only, never `uci revert dhcp`: the user's unrelated
    // staged edits must survive.
    sys.uci_revert_option("dhcp.@dnsmasq[0].noresolv");
    sys.uci_revert_option("dhcp.@dnsmasq[0].server");
    sys.uci_revert_option("dhcp.@dnsmasq[0].resolvfile");

    // LuCI Save&Apply on the DHCP page commits staged deltas wholesale; a
    // committed repoint would outlive a disabled daemon.
    if committed_has_managed_path(&sys.committed_dhcp()) {
        tracing::warn!(
            "Our resolvfile repoint was found committed in /etc/config/dhcp \
             (likely an unrelated dhcp commit); repairing to stock default"
        );
        sys.repair_committed_resolvfile()?;
    }

    let section = sys.dnsmasq_section().ok_or(Error::NoDnsmasq)?;

    // dnsmasq.init emits `resolv-file=` only when noresolv is unset/false.
    if sys.effective_noresolv(&section) {
        tracing::info!(
            "dnsmasq has noresolv set — user manages upstream DNS; \
             leaving it untouched (upstreams ride the tunnel while connected)"
        );
        return Ok(ConvergeOutcome::UserManagedDns);
    }

    for attempt in 0..2u8 {
        sys.uci_set("dhcp.@dnsmasq[0].resolvfile", managed_file)?;

        if extract_instance_pid(&sys.service_json(), &section).is_none() {
            tracing::warn!(
                "dnsmasq is not running; leaving it stopped \
                 (repoint staged for whenever it starts)"
            );
            return Ok(ConvergeOutcome::DnsmasqStopped);
        }

        if sys
            .generated_conf(&section)
            .is_some_and(|conf| generated_conf_points_at(&conf, managed_file))
        {
            return Ok(ConvergeOutcome::Ready);
        }

        sys.restart_dnsmasq()?;

        if sys
            .generated_conf(&section)
            .is_some_and(|conf| generated_conf_points_at(&conf, managed_file))
        {
            return Ok(ConvergeOutcome::Ready);
        }
        // A third-party restart may have raced the revert/re-stage.
        tracing::warn!(
            "dnsmasq generated config did not converge after restart (attempt {}), retrying",
            attempt + 1
        );
    }

    Err(Error::DnsmasqRestart(
        "generated config does not point at managed resolv file after restart".into(),
    ))
}

#[derive(thiserror::Error, Debug)]
pub enum Error {
    #[error("not running on OpenWrt")]
    NotOpenWrt,

    #[error("dnsmasq not configured via UCI")]
    NoDnsmasq,

    #[error("failed to execute UCI command: {0}")]
    UciCommand(String),

    #[error("failed to restart dnsmasq: {0}")]
    DnsmasqRestart(String),

    #[error("failed to write {path}: {source}")]
    WriteFile { path: String, source: io::Error },

    #[error("dnsmasq DNS actor is not running")]
    ActorGone,
}

/// A poll, not inotify: it folds into the single-owner actor loop.
const MIRROR_INTERVAL: Duration = Duration::from_secs(5);

#[derive(Clone)]
struct Paths {
    managed: PathBuf,
    tmp: PathBuf,
    wan: PathBuf,
}

impl Paths {
    fn real() -> Self {
        Paths {
            managed: MANAGED_FILE.into(),
            tmp: MANAGED_TMP.into(),
            wan: WAN_RESOLV.into(),
        }
    }
}

enum Cmd {
    SetTunnel(Vec<IpAddr>, oneshot::Sender<Result<()>>),
    SetWanMirror(IdleDns, oneshot::Sender<Result<()>>),
}

enum Mode {
    Tunnel,
    WanMirror(IdleDns),
}

/// Temp file + rename: dnsmasq's inotify sees exactly one IN_MOVED_TO per
/// update. Never truncate the managed file in place from anywhere.
fn write_managed(paths: &Paths, content: &str) -> Result<()> {
    let wrap = |source: io::Error, path: &PathBuf| Error::WriteFile {
        path: path.display().to_string(),
        source,
    };
    fs::write(&paths.tmp, content).map_err(|e| wrap(e, &paths.tmp))?;
    fs::rename(&paths.tmp, &paths.managed).map_err(|e| wrap(e, &paths.managed))
}

/// Header-only when netifd has not written `resolv.conf.auto` yet.
fn wan_snapshot(paths: &Paths) -> String {
    fs::read_to_string(&paths.wan).unwrap_or_else(|_| String::from("# Generated by nym-vpnd\n"))
}

/// Local resolvers first, then the WAN ones only when reachable; with the
/// kill-switch on dnsmasq would burn its retries on rejected upstreams.
fn idle_snapshot(paths: &Paths, idle: &IdleDns) -> String {
    if idle.local_resolvers.is_empty() {
        return wan_snapshot(paths);
    }
    let mut out = render_resolv_conf(&idle.local_resolvers);
    if idle.includes_wan() {
        for line in wan_snapshot(paths).lines() {
            if line.starts_with("nameserver ") && !out.contains(&format!("{line}\n")) {
                out.push_str(line);
                out.push('\n');
            }
        }
    }
    out
}

/// Answers differ across WAN/tunnel (split-horizon, CDN geo), so the cache
/// is flushed at transitions. The resolv-file reload is inotify's job.
fn flush_cache<S: Sys>(sys: &S, section: &str) {
    match extract_instance_pid(&sys.service_json(), section) {
        Some(pid) => sys.send_hup(pid),
        None => tracing::warn!("Could not determine dnsmasq pid; skipping cache flush"),
    }
}

fn ensure_converged<S: Sys>(
    sys: &S,
    paths: &Paths,
    scheme: &mut Option<Scheme>,
) -> Result<Scheme> {
    if let Some(s) = *scheme {
        return Ok(s);
    }
    let s = match converge(sys, &paths.managed.display().to_string())? {
        ConvergeOutcome::UserManagedDns => Scheme::UserManaged,
        ConvergeOutcome::Ready | ConvergeOutcome::DnsmasqStopped => Scheme::ManagedFile,
    };
    *scheme = Some(s);
    Ok(s)
}

fn handle_set_tunnel<S: Sys>(
    sys: &S,
    paths: &Paths,
    scheme: &mut Option<Scheme>,
    servers: &[IpAddr],
) -> Result<()> {
    let s = ensure_converged(sys, paths, scheme)?;
    let servers = prefer_ipv4_upstreams(servers);
    write_managed(paths, &render_resolv_conf(&servers))?;

    if let Some(section) = sys.dnsmasq_section() {
        match s {
            Scheme::ManagedFile => {
                // A third-party dnsmasq restart may have regenerated the config
                // without our staged delta; full converge only on mismatch.
                let managed = paths.managed.display().to_string();
                let pointed = sys
                    .generated_conf(&section)
                    .is_some_and(|conf| generated_conf_points_at(&conf, &managed));
                if !pointed {
                    tracing::warn!(
                        "dnsmasq no longer points at managed resolv file; re-converging"
                    );
                    *scheme = None;
                    ensure_converged(sys, paths, scheme)?;
                }
            }
            Scheme::UserManaged => {
                // The user may have cleared noresolv since (DoH proxy removed).
                if !sys.effective_noresolv(&section) {
                    tracing::info!("noresolv cleared since last converge; re-converging");
                    *scheme = None;
                    ensure_converged(sys, paths, scheme)?;
                }
            }
        }
        flush_cache(sys, &section);
    }

    match scheme.unwrap_or(s) {
        Scheme::ManagedFile => {
            tracing::info!("Configured dnsmasq with VPN DNS servers: {:?}", servers)
        }
        Scheme::UserManaged => tracing::info!(
            "User-managed dnsmasq upstreams (noresolv) left in place; \
             VPN DNS servers not applied: {:?}",
            servers
        ),
    }
    Ok(())
}

fn handle_set_wan<S: Sys>(sys: &S, paths: &Paths, idle: &IdleDns) -> Result<()> {
    // No converge needed: the mirror is harmless regardless of repoint state.
    write_managed(paths, &idle_snapshot(paths, idle))?;
    if let Some(section) = sys.dnsmasq_section() {
        flush_cache(sys, &section);
    }
    if idle.local_resolvers.is_empty() {
        tracing::info!("Restored dnsmasq to WAN DNS upstreams");
    } else {
        tracing::info!(
            "Pointed dnsmasq at the LAN custom resolvers {:?} while idle{}",
            idle.local_resolvers,
            if idle.includes_wan() {
                ", WAN upstreams kept after them"
            } else {
                "; WAN upstreams dropped (kill-switch on)"
            }
        );
    }
    Ok(())
}

/// Write-if-changed, no cache flush: a WAN DHCP renew must not churn LAN caches.
fn mirror_tick(paths: &Paths, idle: &IdleDns) {
    let wanted = idle_snapshot(paths, idle);
    let current = fs::read_to_string(&paths.managed).unwrap_or_default();
    if wanted != current {
        match write_managed(paths, &wanted) {
            Ok(()) => tracing::debug!("Mirrored WAN resolv change into managed resolv file"),
            Err(e) => tracing::warn!("WAN mirror write failed: {}", e),
        }
    }
}

/// Single writer of the managed file; a tick in `Mode::Tunnel` is dropped, so
/// the mirror can never clobber tunnel resolvers.
async fn run_actor<S: Sys>(sys: S, paths: Paths, mut rx: mpsc::Receiver<Cmd>) {
    migrate_legacy_state();

    // Seed so dnsmasq never observes a missing file. A failed converge is
    // retried on first use.
    if let Err(e) = write_managed(&paths, &wan_snapshot(&paths)) {
        tracing::warn!("Failed to seed managed resolv file: {}", e);
    }
    let mut scheme: Option<Scheme> = None;
    if let Err(e) = ensure_converged(&sys, &paths, &mut scheme) {
        tracing::warn!("dnsmasq converge failed (will retry on first use): {}", e);
    }

    let mut mode = Mode::WanMirror(IdleDns::wan_only());
    let mut tick = tokio::time::interval(MIRROR_INTERVAL);
    tick.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Skip);

    loop {
        tokio::select! {
            cmd = rx.recv() => {
                let Some(cmd) = cmd else { break };
                match cmd {
                    Cmd::SetTunnel(servers, ack) => {
                        let result = handle_set_tunnel(&sys, &paths, &mut scheme, &servers);
                        if result.is_ok() {
                            mode = Mode::Tunnel;
                        }
                        let _ = ack.send(result);
                    }
                    Cmd::SetWanMirror(idle, ack) => {
                        let result = handle_set_wan(&sys, &paths, &idle);
                        if result.is_ok() {
                            mode = Mode::WanMirror(idle);
                        }
                        let _ = ack.send(result);
                    }
                }
            }
            _ = tick.tick() => {
                if let Mode::WanMirror(idle) = &mode {
                    mirror_tick(&paths, idle);
                }
            }
        }
    }
}

/// Restores /etc/resolv.conf from the pre-1.32 backup if one was left behind.
/// Delete once 1.31 and older are out of the upgrade window.
fn migrate_legacy_state() {
    if Path::new(RESOLV_CONF_BACKUP).exists() {
        tracing::info!("Migrating legacy DNS backup state from pre-1.32");
        if let Ok(backup) = fs::read_to_string(RESOLV_CONF_BACKUP) {
            let _ = fs::write(RESOLV_CONF, backup);
        }
        let _ = fs::remove_file(RESOLV_CONF_BACKUP);
    }
    let _ = fs::remove_file(BACKUP_MARKER);
}

static ACTOR: OnceLock<mpsc::Sender<Cmd>> = OnceLock::new();

/// Spawn the actor at startup so its one-time converge (and possible dnsmasq
/// restart) stays off the connect path. No-op outside a tokio runtime.
pub fn warm_up() {
    if tokio::runtime::Handle::try_current().is_err() {
        return;
    }
    match Dnsmasq::new() {
        Ok(_) | Err(Error::NotOpenWrt) => {}
        Err(e) => tracing::debug!("dnsmasq warm-up skipped: {}", e),
    }
}

/// Thin handle, one per connect; all talk to the same daemon-lifetime actor.
pub struct Dnsmasq {
    tx: mpsc::Sender<Cmd>,
}

impl Dnsmasq {
    pub fn new() -> Result<Self> {
        if !Path::new(OPENWRT_RELEASE).exists() {
            return Err(Error::NotOpenWrt);
        }

        let output = Command::new("uci")
            .args(["get", "dhcp.@dnsmasq[0]"])
            .output()
            .map_err(|e| Error::UciCommand(e.to_string()))?;

        if !output.status.success() {
            return Err(Error::NoDnsmasq);
        }

        let tx = ACTOR
            .get_or_init(|| {
                let (tx, rx) = mpsc::channel(8);
                tokio::spawn(run_actor(RealSys, Paths::real(), rx));
                tracing::debug!("OpenWrt dnsmasq DNS actor spawned");
                tx
            })
            .clone();

        Ok(Dnsmasq { tx })
    }

    pub async fn set_dns(&mut self, servers: &[IpAddr]) -> Result<()> {
        let (ack, rx) = oneshot::channel();
        self.tx
            .send(Cmd::SetTunnel(servers.to_vec(), ack))
            .await
            .map_err(|_| Error::ActorGone)?;
        rx.await.map_err(|_| Error::ActorGone)?
    }

    pub async fn reset(&mut self) -> Result<()> {
        self.reset_idle(IdleDns::wan_only()).await
    }

    pub async fn reset_idle(&mut self, idle: IdleDns) -> Result<()> {
        let (ack, rx) = oneshot::channel();
        self.tx
            .send(Cmd::SetWanMirror(idle, ack))
            .await
            .map_err(|_| Error::ActorGone)?;
        rx.await.map_err(|_| Error::ActorGone)?
    }
}

fn uci_set(key: &str, value: &str) -> Result<()> {
    let arg = format!("{}={}", key, value);
    let output = Command::new("uci")
        .args(["set", &arg])
        .output()
        .map_err(|e| Error::UciCommand(e.to_string()))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(Error::UciCommand(format!("uci set {} failed: {}", arg, stderr)));
    }
    Ok(())
}

fn restart_dnsmasq() -> Result<()> {
    let output = Command::new("/etc/init.d/dnsmasq")
        .arg("restart")
        .output()
        .map_err(|e| Error::DnsmasqRestart(e.to_string()))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(Error::DnsmasqRestart(stderr.to_string()));
    }
    Ok(())
}

#[cfg(test)]
mod converge_tests {
    use super::*;
    use std::sync::Mutex;

    #[derive(Default)]
    pub(super) struct FakeSys {
        pub calls: Mutex<Vec<String>>,
        pub committed: String,
        pub section: Option<String>,
        // queue of generated-conf reads, popped front on each generated_conf()
        pub generated: Mutex<Vec<Option<String>>>,
        pub running: bool,
        pub noresolv: bool,
    }

    impl Sys for FakeSys {
        fn uci_revert_option(&self, key: &str) {
            self.calls.lock().unwrap().push(format!("revert {key}"));
        }
        fn uci_set(&self, key: &str, value: &str) -> Result<()> {
            self.calls.lock().unwrap().push(format!("set {key}={value}"));
            Ok(())
        }
        fn repair_committed_resolvfile(&self) -> Result<()> {
            self.calls.lock().unwrap().push("repair-commit".into());
            Ok(())
        }
        fn committed_dhcp(&self) -> String {
            self.committed.clone()
        }
        fn effective_noresolv(&self, _section: &str) -> bool {
            self.calls.lock().unwrap().push("get noresolv".into());
            self.noresolv
        }
        fn dnsmasq_section(&self) -> Option<String> {
            self.section.clone()
        }
        fn generated_conf(&self, _section: &str) -> Option<String> {
            let mut q = self.generated.lock().unwrap();
            if q.is_empty() { None } else { q.remove(0) }
        }
        fn restart_dnsmasq(&self) -> Result<()> {
            self.calls.lock().unwrap().push("restart".into());
            Ok(())
        }
        fn service_json(&self) -> String {
            if self.running {
                r#"{"dnsmasq":{"instances":{"cfg01411c":{"running":true,"pid":42}}}}"#.into()
            } else {
                r#"{"dnsmasq":{"instances":{}}}"#.into()
            }
        }
        fn send_hup(&self, pid: u32) {
            self.calls.lock().unwrap().push(format!("hup {pid}"));
        }
    }

    pub(super) fn managed_line() -> String {
        format!("resolv-file={}\n", MANAGED_FILE)
    }

    #[test]
    fn converge_skips_restart_when_already_pointed() {
        let sys = FakeSys {
            section: Some("cfg01411c".into()),
            generated: Mutex::new(vec![Some(managed_line())]),
            running: true,
            ..Default::default()
        };
        let out = converge(&sys, MANAGED_FILE).unwrap();
        assert!(matches!(out, ConvergeOutcome::Ready));
        let calls = sys.calls.lock().unwrap();
        assert!(
            !calls.iter().any(|c| c == "restart"),
            "must not restart when converged: {calls:?}"
        );
        assert!(calls.iter().any(|c| c.starts_with("revert dhcp.@dnsmasq[0].noresolv")));
    }

    #[test]
    fn converge_restarts_once_and_asserts() {
        let sys = FakeSys {
            section: Some("cfg01411c".into()),
            generated: Mutex::new(vec![
                Some("resolv-file=/tmp/resolv.conf.d/resolv.conf.auto\n".into()), // pre-restart read
                Some(managed_line()),                                             // post-restart assert
            ]),
            running: true,
            ..Default::default()
        };
        assert!(matches!(converge(&sys, MANAGED_FILE).unwrap(), ConvergeOutcome::Ready));
        assert_eq!(
            sys.calls.lock().unwrap().iter().filter(|c| *c == "restart").count(),
            1
        );
    }

    #[test]
    fn converge_leaves_stopped_dnsmasq_stopped() {
        let sys = FakeSys {
            section: Some("cfg01411c".into()),
            generated: Mutex::new(vec![None]),
            running: false,
            ..Default::default()
        };
        assert!(matches!(
            converge(&sys, MANAGED_FILE).unwrap(),
            ConvergeOutcome::DnsmasqStopped
        ));
        assert!(!sys.calls.lock().unwrap().iter().any(|c| c == "restart"));
    }

    #[test]
    fn converge_repairs_committed_accident() {
        let sys = FakeSys {
            committed: "option resolvfile '/tmp/resolv.conf.d/nym-resolv.conf'".into(),
            section: Some("cfg01411c".into()),
            generated: Mutex::new(vec![Some(managed_line())]),
            running: true,
            ..Default::default()
        };
        converge(&sys, MANAGED_FILE).unwrap();
        assert!(sys.calls.lock().unwrap().iter().any(|c| c == "repair-commit"));
    }

    #[test]
    fn converge_noresolv_skips_repoint_and_never_restarts() {
        let sys = FakeSys {
            section: Some("cfg01411c".into()),
            running: true,
            noresolv: true,
            ..Default::default()
        };
        let out = converge(&sys, MANAGED_FILE).unwrap();
        assert!(matches!(out, ConvergeOutcome::UserManagedDns));
        let calls = sys.calls.lock().unwrap();
        assert!(
            !calls.iter().any(|c| c == "restart"),
            "noresolv boxes must never be restarted: {calls:?}"
        );
        assert!(
            !calls.iter().any(|c| c.starts_with("set dhcp.@dnsmasq[0].resolvfile")),
            "no repoint may be staged under noresolv: {calls:?}"
        );
    }

    #[test]
    fn converge_reverts_only_targeted_options() {
        let sys = FakeSys {
            section: Some("cfg01411c".into()),
            generated: Mutex::new(vec![Some(managed_line())]),
            running: true,
            ..Default::default()
        };
        converge(&sys, MANAGED_FILE).unwrap();
        let calls = sys.calls.lock().unwrap();
        let reverts: Vec<_> = calls.iter().filter(|c| c.starts_with("revert")).collect();
        assert_eq!(reverts.len(), 3, "exactly noresolv/server/resolvfile: {reverts:?}");
        assert!(
            !calls.iter().any(|c| *c == "revert dhcp"),
            "wholesale revert forbidden"
        );
    }
}

#[cfg(test)]
mod actor_tests {
    use super::converge_tests::FakeSys;
    use super::*;
    use std::sync::{Arc, Mutex};

    async fn spawn_test_actor(with_wan: bool) -> (
        tokio::sync::mpsc::Sender<Cmd>,
        Paths,
        Arc<FakeSys>,
        tempfile::TempDir,
    ) {
        let dir = tempfile::tempdir().unwrap();
        let paths = Paths {
            managed: dir.path().join("nym-resolv.conf"),
            tmp: dir.path().join(".nym-resolv.tmp"),
            wan: dir.path().join("resolv.conf.auto"),
        };
        if with_wan {
            std::fs::write(&paths.wan, "nameserver 203.0.113.1\n").unwrap();
        }
        let generated_line = format!("resolv-file={}\n", paths.managed.display());
        let sys = Arc::new(FakeSys {
            section: Some("cfg01411c".into()),
            generated: Mutex::new(vec![Some(generated_line); 64]),
            running: true,
            ..Default::default()
        });
        let (tx, rx) = tokio::sync::mpsc::channel(8);
        tokio::spawn(run_actor(sys.clone(), paths.clone(), rx));
        (tx, paths, sys, dir)
    }

    #[tokio::test(start_paused = true)]
    async fn set_tunnel_writes_v4_only_and_flushes_cache() {
        let (tx, paths, sys, _dir) = spawn_test_actor(true).await;
        let (ack, rx) = tokio::sync::oneshot::channel();
        tx.send(Cmd::SetTunnel(
            vec!["2620:fe::fe".parse().unwrap(), "10.64.0.1".parse().unwrap()],
            ack,
        ))
        .await
        .unwrap();
        rx.await.unwrap().unwrap();
        let content = std::fs::read_to_string(&paths.managed).unwrap();
        assert!(content.contains("nameserver 10.64.0.1"));
        assert!(!content.contains("2620:fe::fe"));
        assert!(sys.calls.lock().unwrap().iter().any(|c| c.starts_with("hup ")));
    }

    #[tokio::test(start_paused = true)]
    async fn wan_mirror_tracks_while_disconnected_but_never_while_tunnel() {
        let (tx, paths, _sys, _dir) = spawn_test_actor(true).await;
        // connect
        let (ack, rx) = tokio::sync::oneshot::channel();
        tx.send(Cmd::SetTunnel(vec!["10.64.0.1".parse().unwrap()], ack))
            .await
            .unwrap();
        rx.await.unwrap().unwrap();
        // WAN file changes while connected — mirror must NOT clobber tunnel resolvers
        std::fs::write(&paths.wan, "nameserver 192.0.2.53\n").unwrap();
        tokio::time::sleep(std::time::Duration::from_millis(12_000)).await; // > 2 ticks
        assert!(std::fs::read_to_string(&paths.managed).unwrap().contains("10.64.0.1"));
        // disconnect → mirror mode: WAN content must flow in
        let (ack, rx) = tokio::sync::oneshot::channel();
        tx.send(Cmd::SetWanMirror(IdleDns::wan_only(), ack))
            .await
            .unwrap();
        rx.await.unwrap().unwrap();
        assert!(std::fs::read_to_string(&paths.managed).unwrap().contains("192.0.2.53"));
        // subsequent WAN change tracked by tick
        std::fs::write(&paths.wan, "nameserver 198.51.100.53\n").unwrap();
        tokio::time::sleep(std::time::Duration::from_millis(12_000)).await;
        assert!(std::fs::read_to_string(&paths.managed).unwrap().contains("198.51.100.53"));
    }

    #[tokio::test(start_paused = true)]
    async fn set_tunnel_succeeds_under_noresolv_without_restart() {
        let dir = tempfile::tempdir().unwrap();
        let paths = Paths {
            managed: dir.path().join("nym-resolv.conf"),
            tmp: dir.path().join(".nym-resolv.tmp"),
            wan: dir.path().join("resolv.conf.auto"),
        };
        let sys = Arc::new(FakeSys {
            section: Some("cfg01411c".into()),
            running: true,
            noresolv: true,
            ..Default::default()
        });
        let (tx, rx) = tokio::sync::mpsc::channel(8);
        tokio::spawn(run_actor(sys.clone(), paths, rx));
        let (ack, arx) = tokio::sync::oneshot::channel();
        tx.send(Cmd::SetTunnel(vec!["10.64.0.1".parse().unwrap()], ack))
            .await
            .unwrap();
        arx.await.unwrap().unwrap(); // connect must NOT fail
        let calls = sys.calls.lock().unwrap();
        assert!(!calls.iter().any(|c| c == "restart"), "no restarts: {calls:?}");
        assert!(
            calls.iter().any(|c| c.starts_with("hup ")),
            "cache still flushed at transition: {calls:?}"
        );
    }

    #[tokio::test(start_paused = true)]
    async fn missing_wan_file_is_tolerated() {
        let (tx, paths, _sys, _dir) = spawn_test_actor(false).await;
        let (ack, rx) = tokio::sync::oneshot::channel();
        tx.send(Cmd::SetWanMirror(IdleDns::wan_only(), ack))
            .await
            .unwrap();
        rx.await.unwrap().unwrap(); // must not error
        assert!(paths.managed.exists());
    }

    fn idle(local: &[&str], killswitch: bool) -> IdleDns {
        IdleDns {
            local_resolvers: local.iter().map(|s| s.parse().unwrap()).collect(),
            killswitch,
        }
    }

    #[test]
    fn idle_snapshot_without_local_resolvers_is_the_wan_mirror() {
        let dir = tempfile::tempdir().unwrap();
        let paths = Paths {
            managed: dir.path().join("nym-resolv.conf"),
            tmp: dir.path().join(".nym-resolv.tmp"),
            wan: dir.path().join("resolv.conf.auto"),
        };
        std::fs::write(&paths.wan, "# Interface wan\nnameserver 203.0.113.1\n").unwrap();
        assert_eq!(
            idle_snapshot(&paths, &idle(&[], true)),
            wan_snapshot(&paths)
        );
        assert_eq!(
            idle_snapshot(&paths, &idle(&[], false)),
            wan_snapshot(&paths)
        );
    }

    #[test]
    fn idle_snapshot_with_local_resolver_and_killswitch_on_drops_the_wan() {
        let dir = tempfile::tempdir().unwrap();
        let paths = Paths {
            managed: dir.path().join("nym-resolv.conf"),
            tmp: dir.path().join(".nym-resolv.tmp"),
            wan: dir.path().join("resolv.conf.auto"),
        };
        std::fs::write(&paths.wan, "nameserver 203.0.113.1\n").unwrap();
        let content = idle_snapshot(&paths, &idle(&["10.10.10.178"], true));
        assert_eq!(
            content,
            "# Generated by nym-vpnd\nnameserver 10.10.10.178\n"
        );
    }

    #[test]
    fn idle_snapshot_with_local_resolver_and_killswitch_off_keeps_the_wan_after_it() {
        let dir = tempfile::tempdir().unwrap();
        let paths = Paths {
            managed: dir.path().join("nym-resolv.conf"),
            tmp: dir.path().join(".nym-resolv.tmp"),
            wan: dir.path().join("resolv.conf.auto"),
        };
        std::fs::write(
            &paths.wan,
            "# Interface wan\nnameserver 203.0.113.1\nnameserver 10.10.10.178\n",
        )
        .unwrap();
        let content = idle_snapshot(&paths, &idle(&["10.10.10.178"], false));
        assert_eq!(
            content, "# Generated by nym-vpnd\nnameserver 10.10.10.178\nnameserver 203.0.113.1\n",
            "local first, WAN appended, duplicates dropped"
        );
    }

    #[tokio::test(start_paused = true)]
    async fn idle_mirror_keeps_only_the_lan_resolver_across_wan_changes() {
        let (tx, paths, _sys, _dir) = spawn_test_actor(true).await;
        let (ack, rx) = tokio::sync::oneshot::channel();
        tx.send(Cmd::SetWanMirror(idle(&["10.10.10.178"], true), ack))
            .await
            .unwrap();
        rx.await.unwrap().unwrap();
        let content = std::fs::read_to_string(&paths.managed).unwrap();
        assert!(content.contains("nameserver 10.10.10.178"));
        assert!(!content.contains("203.0.113.1"));
        // A WAN DHCP renew while idle must not reintroduce rejected upstreams.
        std::fs::write(&paths.wan, "nameserver 192.0.2.53\n").unwrap();
        tokio::time::sleep(std::time::Duration::from_millis(12_000)).await;
        let content = std::fs::read_to_string(&paths.managed).unwrap();
        assert_eq!(
            content,
            "# Generated by nym-vpnd\nnameserver 10.10.10.178\n"
        );
    }

    #[test]
    fn managed_updates_use_rename_not_truncate() {
        let dir = tempfile::tempdir().unwrap();
        let paths = Paths {
            managed: dir.path().join("m"),
            tmp: dir.path().join(".t"),
            wan: dir.path().join("w"),
        };
        write_managed(&paths, "nameserver 10.0.0.1\n").unwrap();
        assert_eq!(
            std::fs::read_to_string(&paths.managed).unwrap(),
            "nameserver 10.0.0.1\n"
        );
        assert!(!paths.tmp.exists(), "temp file must not linger after rename");
    }
}

#[cfg(test)]
mod tests {
    use super::converge_tests::FakeSys;
    use super::prefer_ipv4_upstreams;
    use std::net::IpAddr;

    #[test]
    fn prefers_ipv4_upstreams_when_mixed() {
        let servers: Vec<IpAddr> = vec![
            "2620:fe::fe".parse().unwrap(),
            "9.9.9.9".parse().unwrap(),
            "2606:4700:4700::1111".parse().unwrap(),
            "1.1.1.1".parse().unwrap(),
        ];
        let got = prefer_ipv4_upstreams(&servers);
        assert_eq!(
            got,
            vec!["9.9.9.9".parse::<IpAddr>().unwrap(), "1.1.1.1".parse().unwrap()]
        );
    }

    #[test]
    fn keeps_ipv6_when_no_ipv4_available() {
        let servers: Vec<IpAddr> = vec!["2620:fe::fe".parse().unwrap()];
        assert_eq!(prefer_ipv4_upstreams(&servers), servers);
    }

    #[test]
    fn renders_resolv_conf() {
        let servers: Vec<IpAddr> = vec!["10.0.0.1".parse().unwrap(), "10.0.0.2".parse().unwrap()];
        assert_eq!(
            super::render_resolv_conf(&servers),
            "# Generated by nym-vpnd\nnameserver 10.0.0.1\nnameserver 10.0.0.2\n"
        );
    }

    #[test]
    fn detects_managed_resolv_file_in_generated_conf() {
        let conf = "server=1.1.1.1\nresolv-file=/tmp/resolv.conf.d/nym-resolv.conf\ncache-size=1000\n";
        assert!(super::generated_conf_points_at(conf, super::MANAGED_FILE));
        let stock = "resolv-file=/tmp/resolv.conf.d/resolv.conf.auto\n";
        assert!(!super::generated_conf_points_at(stock, super::MANAGED_FILE));
        // substring must not fool it
        let tricky = "# resolv-file=/tmp/resolv.conf.d/nym-resolv.conf.bak\n";
        assert!(!super::generated_conf_points_at(tricky, super::MANAGED_FILE));
    }

    #[test]
    fn detects_accidentally_committed_repoint() {
        let dirty = "config dnsmasq\n\toption resolvfile '/tmp/resolv.conf.d/nym-resolv.conf'\n";
        assert!(super::committed_has_managed_path(dirty));
        let clean = "config dnsmasq\n\toption resolvfile '/tmp/resolv.conf.d/resolv.conf.auto'\n";
        assert!(!super::committed_has_managed_path(clean));
    }

    #[test]
    fn parses_dnsmasq_section_from_raw_uci_show() {
        // `uci -X show dhcp` emits raw ids; the extended default (@dnsmasq[0])
        // would not match procd's instance key.
        let show = "dhcp.cfg01411c=dnsmasq\ndhcp.cfg01411c.domainneeded='1'\ndhcp.lan=dhcp\n";
        assert_eq!(super::parse_dnsmasq_section(show), Some("cfg01411c".into()));
        assert_eq!(super::parse_dnsmasq_section("dhcp.lan=dhcp\n"), None);
    }

    #[test]
    fn extracts_ujail_wrapper_pid_from_ubus_json() {
        let json = r#"{ "dnsmasq": { "instances": { "cfg01411c": { "running": true, "pid": 2994, "command": ["x"] } } } }"#;
        assert_eq!(super::extract_instance_pid(json, "cfg01411c"), Some(2994));
        assert_eq!(super::extract_instance_pid(json, "cfg99"), None);
        assert_eq!(super::extract_instance_pid("not json", "cfg01411c"), None);
    }

    #[test]
    fn reports_user_ownership_under_noresolv() {
        let sys = FakeSys {
            section: Some("cfg01411c".into()),
            noresolv: true,
            ..Default::default()
        };
        assert_eq!(super::upstream_owner(&sys), super::UpstreamOwner::User);
    }

    #[test]
    fn reports_vpn_ownership_without_noresolv() {
        let sys = FakeSys {
            section: Some("cfg01411c".into()),
            noresolv: false,
            ..Default::default()
        };
        assert_eq!(super::upstream_owner(&sys), super::UpstreamOwner::Vpn);
    }

    #[test]
    fn reports_not_applicable_without_dnsmasq() {
        let sys = FakeSys {
            section: None,
            noresolv: true,
            ..Default::default()
        };
        assert_eq!(
            super::upstream_owner(&sys),
            super::UpstreamOwner::NotApplicable
        );
    }

    /// A `dns get` must never converge or restart dnsmasq.
    #[test]
    fn ownership_query_never_mutates_system_state() {
        let sys = FakeSys {
            section: Some("cfg01411c".into()),
            noresolv: true,
            ..Default::default()
        };
        super::upstream_owner(&sys);
        let calls = sys.calls.lock().unwrap().clone();
        assert_eq!(
            calls,
            vec!["get noresolv".to_string()],
            "status query must only read noresolv: {calls:?}"
        );
    }
}
