// Copyright 2025 Nym Technologies SA <contact@nymtech.net>
// SPDX-License-Identifier: GPL-3.0-only

//! OpenWrt dnsmasq DNS backend.
//!
//! Configures dnsmasq upstream servers via UCI commands and writes
//! `/etc/resolv.conf` for local programs (nslookup, curl, etc.).
//!
//! Key design: uses `uci set` without `uci commit`, so changes go to
//! the staging area (`/tmp/.uci/dhcp`). On reboot, the staging area
//! is cleared and dnsmasq automatically reverts to original config.

use std::{
    fs, io,
    net::IpAddr,
    path::Path,
    process::Command,
};

pub type Result<T> = std::result::Result<T, Error>;

/// Prefer IPv4 upstream resolvers when both families are present. IPv6
/// upstreams are only reachable when the exit gateway actually carries IPv6,
/// which cannot be verified from the router; unreachable IPv6 upstreams cause
/// per-lookup timeouts in dnsmasq. AAAA records still resolve fine over IPv4
/// transport, so dropping the IPv6 upstreams loses nothing.
fn prefer_ipv4_upstreams(servers: &[std::net::IpAddr]) -> Vec<std::net::IpAddr> {
    let v4: Vec<std::net::IpAddr> = servers.iter().copied().filter(|ip| ip.is_ipv4()).collect();
    if v4.is_empty() { servers.to_vec() } else { v4 }
}

const OPENWRT_RELEASE: &str = "/etc/openwrt_release";
const BACKUP_MARKER: &str = "/tmp/nym-dns-backup";
const RESOLV_CONF: &str = "/etc/resolv.conf";
const RESOLV_CONF_BACKUP: &str = "/tmp/resolv.conf.nymbackup";

/// The daemon-managed resolv file dnsmasq is repointed at. MUST live inside
/// /tmp/resolv.conf.d/: the dnsmasq init script bind-mounts that directory
/// into the ujail (it mounts dirname(resolvfile)), so a file anywhere else
/// would be invisible to the jailed process. It is always a regular file,
/// never a symlink: dnsmasq's inotify build resolves the watch name once at
/// startup, so symlink swaps stop being observed.
const MANAGED_FILE: &str = "/tmp/resolv.conf.d/nym-resolv.conf";
/// Rename source for atomic updates. Basename must not match MANAGED_FILE's
/// (dnsmasq watches the directory by name; the temp write must not trigger).
const MANAGED_TMP: &str = "/tmp/resolv.conf.d/.nym-resolv.tmp";
/// netifd-owned WAN resolv file, mirrored into MANAGED_FILE while disconnected.
const WAN_RESOLV: &str = "/tmp/resolv.conf.d/resolv.conf.auto";

fn render_resolv_conf(servers: &[IpAddr]) -> String {
    let mut out = String::from("# Generated by nym-vpnd\n");
    for server in servers {
        out.push_str(&format!("nameserver {}\n", server));
    }
    out
}

fn generated_conf_points_at(conf: &str, managed_path: &str) -> bool {
    conf.lines()
        .any(|line| line.trim() == format!("resolv-file={}", managed_path))
}

fn committed_has_managed_path(committed_dhcp: &str) -> bool {
    committed_dhcp.contains("nym-resolv.conf")
}

/// Minimal extraction of the instance pid from `ubus call service list` output.
/// Deliberately not a JSON parser: the shape is stable procd output and we
/// only need one integer; a serde dependency isn't warranted. The pid procd
/// reports is the ujail wrapper's, which forwards SIGHUP to the jailed
/// dnsmasq. Never read the dnsmasq pidfile instead — it contains the PID as
/// seen inside the jail's own PID namespace (i.e. "1").
fn extract_instance_pid(service_json: &str, section: &str) -> Option<u32> {
    let inst = service_json.find(&format!("\"{}\"", section))?;
    let rest = &service_json[inst..];
    let pid_key = rest.find("\"pid\"")?;
    let after = &rest[pid_key + 5..];
    let digits: String = after
        .chars()
        .skip_while(|c| !c.is_ascii_digit())
        .take_while(|c| c.is_ascii_digit())
        .collect();
    digits.parse().ok()
}

/// System interaction boundary, mockable for tests.
trait Sys: Send + Sync + 'static {
    /// Targeted `uci revert` of a single option. Best-effort: reverting an
    /// option that has no staged delta fails harmlessly.
    fn uci_revert_option(&self, key: &str);
    /// `uci set` — staged only, never committed.
    fn uci_set(&self, key: &str, value: &str) -> Result<()>;
    /// The ONE allowed commit: delete an accidentally-committed resolvfile
    /// option (restores the stock default) and commit dhcp.
    fn repair_committed_resolvfile(&self) -> Result<()>;
    /// Contents of the committed /etc/config/dhcp ("" if unreadable).
    fn committed_dhcp(&self) -> String;
    /// First uci section of type dnsmasq, e.g. "cfg01411c".
    fn dnsmasq_section(&self) -> Option<String>;
    /// Contents of the generated /var/etc/dnsmasq.conf.<section>.
    fn generated_conf(&self, section: &str) -> Option<String>;
    fn restart_dnsmasq(&self) -> Result<()>;
    /// `ubus call service list '{"name":"dnsmasq"}'` output.
    fn service_json(&self) -> String;
    /// SIGHUP the ujail wrapper (cache flush only — with polling on, dnsmasq
    /// does NOT re-read resolv files on SIGHUP; reload is carried by inotify.
    /// Side effects: re-reads /etc/hosts and runs the lease script per lease).
    fn send_hup(&self, pid: u32);
}

impl<T: Sys> Sys for std::sync::Arc<T> {
    fn uci_revert_option(&self, key: &str) {
        (**self).uci_revert_option(key)
    }
    fn uci_set(&self, key: &str, value: &str) -> Result<()> {
        (**self).uci_set(key, value)
    }
    fn repair_committed_resolvfile(&self) -> Result<()> {
        (**self).repair_committed_resolvfile()
    }
    fn committed_dhcp(&self) -> String {
        (**self).committed_dhcp()
    }
    fn dnsmasq_section(&self) -> Option<String> {
        (**self).dnsmasq_section()
    }
    fn generated_conf(&self, section: &str) -> Option<String> {
        (**self).generated_conf(section)
    }
    fn restart_dnsmasq(&self) -> Result<()> {
        (**self).restart_dnsmasq()
    }
    fn service_json(&self) -> String {
        (**self).service_json()
    }
    fn send_hup(&self, pid: u32) {
        (**self).send_hup(pid)
    }
}

struct RealSys;

impl Sys for RealSys {
    fn uci_revert_option(&self, key: &str) {
        let output = Command::new("uci").args(["revert", key]).output();
        if let Err(e) = output {
            tracing::warn!("uci revert {} failed to execute: {}", key, e);
        }
    }

    fn uci_set(&self, key: &str, value: &str) -> Result<()> {
        uci_set(key, value)
    }

    fn repair_committed_resolvfile(&self) -> Result<()> {
        let run = |args: &[&str]| -> Result<()> {
            let output = Command::new("uci")
                .args(args)
                .output()
                .map_err(|e| Error::UciCommand(e.to_string()))?;
            if !output.status.success() {
                let stderr = String::from_utf8_lossy(&output.stderr);
                return Err(Error::UciCommand(format!("uci {:?} failed: {}", args, stderr)));
            }
            Ok(())
        };
        run(&["delete", "dhcp.@dnsmasq[0].resolvfile"])?;
        run(&["commit", "dhcp"])
    }

    fn committed_dhcp(&self) -> String {
        fs::read_to_string("/etc/config/dhcp").unwrap_or_default()
    }

    fn dnsmasq_section(&self) -> Option<String> {
        let output = Command::new("uci").args(["show", "dhcp"]).output().ok()?;
        let stdout = String::from_utf8_lossy(&output.stdout);
        stdout.lines().find_map(|line| {
            let (key, value) = line.split_once('=')?;
            if value == "dnsmasq" {
                key.strip_prefix("dhcp.").map(str::to_owned)
            } else {
                None
            }
        })
    }

    fn generated_conf(&self, section: &str) -> Option<String> {
        fs::read_to_string(format!("/var/etc/dnsmasq.conf.{}", section)).ok()
    }

    fn restart_dnsmasq(&self) -> Result<()> {
        restart_dnsmasq()
    }

    fn service_json(&self) -> String {
        Command::new("ubus")
            .args(["call", "service", "list", r#"{"name":"dnsmasq"}"#])
            .output()
            .map(|o| String::from_utf8_lossy(&o.stdout).into_owned())
            .unwrap_or_default()
    }

    fn send_hup(&self, pid: u32) {
        // BusyBox kill; avoids a libc dependency for one signal.
        let result = Command::new("kill").args(["-HUP", &pid.to_string()]).output();
        match result {
            Ok(o) if o.status.success() => {}
            Ok(o) => tracing::warn!(
                "kill -HUP {} failed: {}",
                pid,
                String::from_utf8_lossy(&o.stderr)
            ),
            Err(e) => tracing::warn!("kill -HUP {} failed to execute: {}", pid, e),
        }
    }
}

enum ConvergeOutcome {
    /// dnsmasq is running and its generated config points at the managed file.
    Ready,
    /// The repoint is staged but dnsmasq is administratively stopped; we leave
    /// it stopped (it will pick up the staged config whenever it starts).
    DnsmasqStopped,
}

/// Idempotently converge system state onto the managed-resolv-file scheme.
/// Safe to run on every daemon start: it only restarts dnsmasq when the
/// running instance's generated config does not already point at the managed
/// file, so a crash-looping daemon cannot turn into a dnsmasq restart storm.
/// This is also the crash-recovery path — there is no separate marker.
fn converge<S: Sys>(sys: &S, managed_file: &str) -> Result<ConvergeOutcome> {
    // Targeted reverts: clears the legacy (≤1.31) staged noresolv/server-list
    // scheme and any stale repoint of our own, without discarding the user's
    // unrelated staged dhcp edits (never `uci revert dhcp` wholesale).
    sys.uci_revert_option("dhcp.@dnsmasq[0].noresolv");
    sys.uci_revert_option("dhcp.@dnsmasq[0].server");
    sys.uci_revert_option("dhcp.@dnsmasq[0].resolvfile");

    // Repair an accidentally-committed repoint (LuCI Save&Apply on the DHCP
    // page commits staged deltas wholesale). Deleting the option restores the
    // stock default; without this, a reboot with the daemon disabled would
    // leave dnsmasq pointing at a file nothing maintains.
    if committed_has_managed_path(&sys.committed_dhcp()) {
        tracing::warn!(
            "Our resolvfile repoint was found committed in /etc/config/dhcp \
             (likely an unrelated dhcp commit); repairing to stock default"
        );
        sys.repair_committed_resolvfile()?;
    }

    let section = sys.dnsmasq_section().ok_or(Error::NoDnsmasq)?;

    for attempt in 0..2u8 {
        sys.uci_set("dhcp.@dnsmasq[0].resolvfile", managed_file)?;

        if extract_instance_pid(&sys.service_json(), &section).is_none() {
            tracing::warn!(
                "dnsmasq is not running; leaving it stopped \
                 (repoint staged for whenever it starts)"
            );
            return Ok(ConvergeOutcome::DnsmasqStopped);
        }

        if sys
            .generated_conf(&section)
            .is_some_and(|conf| generated_conf_points_at(&conf, managed_file))
        {
            return Ok(ConvergeOutcome::Ready);
        }

        sys.restart_dnsmasq()?;

        if sys
            .generated_conf(&section)
            .is_some_and(|conf| generated_conf_points_at(&conf, managed_file))
        {
            return Ok(ConvergeOutcome::Ready);
        }
        // A third-party restart may have raced between our revert and re-stage,
        // regenerating the config from an intermediate state. Retry once.
        tracing::warn!(
            "dnsmasq generated config did not converge after restart (attempt {}), retrying",
            attempt + 1
        );
    }

    Err(Error::DnsmasqRestart(
        "generated config does not point at managed resolv file after restart".into(),
    ))
}

#[derive(thiserror::Error, Debug)]
pub enum Error {
    #[error("not running on OpenWrt")]
    NotOpenWrt,

    #[error("dnsmasq not configured via UCI")]
    NoDnsmasq,

    #[error("failed to execute UCI command: {0}")]
    UciCommand(String),

    #[error("failed to restart dnsmasq: {0}")]
    DnsmasqRestart(String),

    #[error("failed to write {path}: {source}")]
    WriteFile {
        path: &'static str,
        source: io::Error,
    },

    #[error("failed to read {path}: {source}")]
    ReadFile {
        path: &'static str,
        source: io::Error,
    },
}

pub struct Dnsmasq {
    /// Whether set_dns has been called (backup already created).
    configured: bool,
}

impl Dnsmasq {
    pub fn new() -> Result<Self> {
        // Check if we're on OpenWrt
        if !Path::new(OPENWRT_RELEASE).exists() {
            return Err(Error::NotOpenWrt);
        }

        // Check if dnsmasq is configured via UCI
        let output = Command::new("uci")
            .args(["get", "dhcp.@dnsmasq[0]"])
            .output()
            .map_err(|e| Error::UciCommand(e.to_string()))?;

        if !output.status.success() {
            return Err(Error::NoDnsmasq);
        }

        // Crash recovery: if backup marker exists, a previous session didn't clean up
        if Path::new(BACKUP_MARKER).exists() {
            tracing::info!("Found stale DNS backup, recovering previous state");
            if let Err(e) = Self::do_reset() {
                tracing::warn!("Crash recovery partial failure: {}", e);
            }
        }

        tracing::debug!("OpenWrt dnsmasq DNS backend initialized");
        Ok(Dnsmasq { configured: false })
    }

    pub fn set_dns(&mut self, servers: &[IpAddr]) -> Result<()> {
        if !self.configured {
            // First call: save current state
            self.save_backup()?;
            self.configured = true;
        }

        let servers = prefer_ipv4_upstreams(servers);
        let servers = servers.as_slice();

        // Set noresolv so dnsmasq ignores /tmp/resolv.conf.d/resolv.conf.auto
        uci_set("dhcp.@dnsmasq[0].noresolv", "1")?;

        // Clear existing server list
        // `uci delete` on a list option removes the entire list.
        // It's not an error if the option doesn't exist yet.
        let _ = uci_delete("dhcp.@dnsmasq[0].server");

        // Add each VPN DNS server
        for server in servers {
            uci_add_list("dhcp.@dnsmasq[0].server", &server.to_string())?;
        }

        // Write /etc/resolv.conf for local programs
        self.write_resolv_conf(servers)?;

        // Restart dnsmasq to pick up changes
        restart_dnsmasq()?;

        tracing::info!(
            "Configured dnsmasq with VPN DNS servers: {:?}",
            servers
        );

        Ok(())
    }

    pub fn reset(&mut self) -> Result<()> {
        if !self.configured {
            return Ok(());
        }

        Self::do_reset()?;
        self.configured = false;

        tracing::info!("Restored dnsmasq to original DNS configuration");
        Ok(())
    }

    /// Shared reset logic used by both `reset()` and crash recovery.
    fn do_reset() -> Result<()> {
        // Revert all staged UCI changes for dhcp — restores original config
        uci_revert("dhcp")?;

        // Restore /etc/resolv.conf from backup
        if Path::new(RESOLV_CONF_BACKUP).exists() {
            match fs::read_to_string(RESOLV_CONF_BACKUP) {
                Ok(backup) => {
                    fs::write(RESOLV_CONF, backup.as_bytes()).map_err(|e| Error::WriteFile {
                        path: RESOLV_CONF,
                        source: e,
                    })?;
                }
                Err(e) => {
                    tracing::warn!("Failed to read resolv.conf backup: {}", e);
                }
            }
            let _ = fs::remove_file(RESOLV_CONF_BACKUP);
        }

        // Restart dnsmasq with restored config
        restart_dnsmasq()?;

        // Remove backup marker
        let _ = fs::remove_file(BACKUP_MARKER);

        Ok(())
    }

    /// Save current UCI state and resolv.conf so we can restore on reset.
    fn save_backup(&self) -> Result<()> {
        // Save current noresolv and server values as a simple marker.
        // The actual restore uses `uci revert` which discards staged changes,
        // so we don't need to store the full UCI state — just a marker that
        // we modified things.
        fs::write(BACKUP_MARKER, b"active").map_err(|e| Error::WriteFile {
            path: BACKUP_MARKER,
            source: e,
        })?;

        // Backup /etc/resolv.conf
        if Path::new(RESOLV_CONF).exists() {
            let contents = fs::read_to_string(RESOLV_CONF).map_err(|e| Error::ReadFile {
                path: RESOLV_CONF,
                source: e,
            })?;
            fs::write(RESOLV_CONF_BACKUP, contents.as_bytes()).map_err(|e| Error::WriteFile {
                path: RESOLV_CONF_BACKUP,
                source: e,
            })?;
        }

        Ok(())
    }

    /// Write /etc/resolv.conf with the VPN nameservers.
    fn write_resolv_conf(&self, servers: &[IpAddr]) -> Result<()> {
        let mut contents = String::from("# Generated by nym-vpnd\n");
        for server in servers {
            contents.push_str(&format!("nameserver {}\n", server));
        }
        fs::write(RESOLV_CONF, contents.as_bytes()).map_err(|e| Error::WriteFile {
            path: RESOLV_CONF,
            source: e,
        })
    }
}

/// Run `uci set <key>=<value>` (staged, not committed).
fn uci_set(key: &str, value: &str) -> Result<()> {
    let arg = format!("{}={}", key, value);
    let output = Command::new("uci")
        .args(["set", &arg])
        .output()
        .map_err(|e| Error::UciCommand(e.to_string()))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(Error::UciCommand(format!("uci set {} failed: {}", arg, stderr)));
    }
    Ok(())
}

/// Run `uci delete <key>`. Returns Ok even if the key doesn't exist.
fn uci_delete(key: &str) -> Result<()> {
    let output = Command::new("uci")
        .args(["delete", key])
        .output()
        .map_err(|e| Error::UciCommand(e.to_string()))?;

    // uci delete returns non-zero if the entry doesn't exist, which is fine
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        tracing::debug!("uci delete {} (may not exist): {}", key, stderr);
    }
    Ok(())
}

/// Run `uci add_list <key>=<value>` (staged, not committed).
fn uci_add_list(key: &str, value: &str) -> Result<()> {
    let arg = format!("{}={}", key, value);
    let output = Command::new("uci")
        .args(["add_list", &arg])
        .output()
        .map_err(|e| Error::UciCommand(e.to_string()))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(Error::UciCommand(format!(
            "uci add_list {} failed: {}",
            arg, stderr
        )));
    }
    Ok(())
}

/// Run `uci revert <config>` to discard all staged changes.
fn uci_revert(config: &str) -> Result<()> {
    let output = Command::new("uci")
        .args(["revert", config])
        .output()
        .map_err(|e| Error::UciCommand(e.to_string()))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(Error::UciCommand(format!(
            "uci revert {} failed: {}",
            config, stderr
        )));
    }
    Ok(())
}

/// Restart dnsmasq via its init script.
fn restart_dnsmasq() -> Result<()> {
    let output = Command::new("/etc/init.d/dnsmasq")
        .arg("restart")
        .output()
        .map_err(|e| Error::DnsmasqRestart(e.to_string()))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(Error::DnsmasqRestart(stderr.to_string()));
    }
    Ok(())
}

#[cfg(test)]
mod converge_tests {
    use super::*;
    use std::sync::Mutex;

    #[derive(Default)]
    pub(super) struct FakeSys {
        pub calls: Mutex<Vec<String>>,
        pub committed: String,
        pub section: Option<String>,
        // queue of generated-conf reads, popped front on each generated_conf()
        pub generated: Mutex<Vec<Option<String>>>,
        pub running: bool,
        pub wan_content: Mutex<Option<String>>,
    }

    impl Sys for FakeSys {
        fn uci_revert_option(&self, key: &str) {
            self.calls.lock().unwrap().push(format!("revert {key}"));
        }
        fn uci_set(&self, key: &str, value: &str) -> Result<()> {
            self.calls.lock().unwrap().push(format!("set {key}={value}"));
            Ok(())
        }
        fn repair_committed_resolvfile(&self) -> Result<()> {
            self.calls.lock().unwrap().push("repair-commit".into());
            Ok(())
        }
        fn committed_dhcp(&self) -> String {
            self.committed.clone()
        }
        fn dnsmasq_section(&self) -> Option<String> {
            self.section.clone()
        }
        fn generated_conf(&self, _section: &str) -> Option<String> {
            let mut q = self.generated.lock().unwrap();
            if q.is_empty() { None } else { q.remove(0) }
        }
        fn restart_dnsmasq(&self) -> Result<()> {
            self.calls.lock().unwrap().push("restart".into());
            Ok(())
        }
        fn service_json(&self) -> String {
            if self.running {
                r#"{"dnsmasq":{"instances":{"cfg01411c":{"running":true,"pid":42}}}}"#.into()
            } else {
                r#"{"dnsmasq":{"instances":{}}}"#.into()
            }
        }
        fn send_hup(&self, pid: u32) {
            self.calls.lock().unwrap().push(format!("hup {pid}"));
        }
    }

    pub(super) fn managed_line() -> String {
        format!("resolv-file={}\n", MANAGED_FILE)
    }

    #[test]
    fn converge_skips_restart_when_already_pointed() {
        let sys = FakeSys {
            section: Some("cfg01411c".into()),
            generated: Mutex::new(vec![Some(managed_line())]),
            running: true,
            ..Default::default()
        };
        let out = converge(&sys, MANAGED_FILE).unwrap();
        assert!(matches!(out, ConvergeOutcome::Ready));
        let calls = sys.calls.lock().unwrap();
        assert!(
            !calls.iter().any(|c| c == "restart"),
            "must not restart when converged: {calls:?}"
        );
        assert!(calls.iter().any(|c| c.starts_with("revert dhcp.@dnsmasq[0].noresolv")));
    }

    #[test]
    fn converge_restarts_once_and_asserts() {
        let sys = FakeSys {
            section: Some("cfg01411c".into()),
            generated: Mutex::new(vec![
                Some("resolv-file=/tmp/resolv.conf.d/resolv.conf.auto\n".into()), // pre-restart read
                Some(managed_line()),                                             // post-restart assert
            ]),
            running: true,
            ..Default::default()
        };
        assert!(matches!(converge(&sys, MANAGED_FILE).unwrap(), ConvergeOutcome::Ready));
        assert_eq!(
            sys.calls.lock().unwrap().iter().filter(|c| *c == "restart").count(),
            1
        );
    }

    #[test]
    fn converge_leaves_stopped_dnsmasq_stopped() {
        let sys = FakeSys {
            section: Some("cfg01411c".into()),
            generated: Mutex::new(vec![None]),
            running: false,
            ..Default::default()
        };
        assert!(matches!(
            converge(&sys, MANAGED_FILE).unwrap(),
            ConvergeOutcome::DnsmasqStopped
        ));
        assert!(!sys.calls.lock().unwrap().iter().any(|c| c == "restart"));
    }

    #[test]
    fn converge_repairs_committed_accident() {
        let sys = FakeSys {
            committed: "option resolvfile '/tmp/resolv.conf.d/nym-resolv.conf'".into(),
            section: Some("cfg01411c".into()),
            generated: Mutex::new(vec![Some(managed_line())]),
            running: true,
            ..Default::default()
        };
        converge(&sys, MANAGED_FILE).unwrap();
        assert!(sys.calls.lock().unwrap().iter().any(|c| c == "repair-commit"));
    }

    #[test]
    fn converge_reverts_only_targeted_options() {
        let sys = FakeSys {
            section: Some("cfg01411c".into()),
            generated: Mutex::new(vec![Some(managed_line())]),
            running: true,
            ..Default::default()
        };
        converge(&sys, MANAGED_FILE).unwrap();
        let calls = sys.calls.lock().unwrap();
        let reverts: Vec<_> = calls.iter().filter(|c| c.starts_with("revert")).collect();
        assert_eq!(reverts.len(), 3, "exactly noresolv/server/resolvfile: {reverts:?}");
        assert!(
            !calls.iter().any(|c| *c == "revert dhcp"),
            "wholesale revert forbidden"
        );
    }
}

#[cfg(test)]
mod tests {
    use super::prefer_ipv4_upstreams;
    use std::net::IpAddr;

    #[test]
    fn prefers_ipv4_upstreams_when_mixed() {
        let servers: Vec<IpAddr> = vec![
            "2620:fe::fe".parse().unwrap(),
            "9.9.9.9".parse().unwrap(),
            "2606:4700:4700::1111".parse().unwrap(),
            "1.1.1.1".parse().unwrap(),
        ];
        let got = prefer_ipv4_upstreams(&servers);
        assert_eq!(
            got,
            vec!["9.9.9.9".parse::<IpAddr>().unwrap(), "1.1.1.1".parse().unwrap()]
        );
    }

    #[test]
    fn keeps_ipv6_when_no_ipv4_available() {
        let servers: Vec<IpAddr> = vec!["2620:fe::fe".parse().unwrap()];
        assert_eq!(prefer_ipv4_upstreams(&servers), servers);
    }

    #[test]
    fn renders_resolv_conf() {
        let servers: Vec<IpAddr> = vec!["10.0.0.1".parse().unwrap(), "10.0.0.2".parse().unwrap()];
        assert_eq!(
            super::render_resolv_conf(&servers),
            "# Generated by nym-vpnd\nnameserver 10.0.0.1\nnameserver 10.0.0.2\n"
        );
    }

    #[test]
    fn detects_managed_resolv_file_in_generated_conf() {
        let conf = "server=1.1.1.1\nresolv-file=/tmp/resolv.conf.d/nym-resolv.conf\ncache-size=1000\n";
        assert!(super::generated_conf_points_at(conf, super::MANAGED_FILE));
        let stock = "resolv-file=/tmp/resolv.conf.d/resolv.conf.auto\n";
        assert!(!super::generated_conf_points_at(stock, super::MANAGED_FILE));
        // substring must not fool it
        let tricky = "# resolv-file=/tmp/resolv.conf.d/nym-resolv.conf.bak\n";
        assert!(!super::generated_conf_points_at(tricky, super::MANAGED_FILE));
    }

    #[test]
    fn detects_accidentally_committed_repoint() {
        let dirty = "config dnsmasq\n\toption resolvfile '/tmp/resolv.conf.d/nym-resolv.conf'\n";
        assert!(super::committed_has_managed_path(dirty));
        let clean = "config dnsmasq\n\toption resolvfile '/tmp/resolv.conf.d/resolv.conf.auto'\n";
        assert!(!super::committed_has_managed_path(clean));
    }

    #[test]
    fn extracts_ujail_wrapper_pid_from_ubus_json() {
        let json = r#"{ "dnsmasq": { "instances": { "cfg01411c": { "running": true, "pid": 2994, "command": ["x"] } } } }"#;
        assert_eq!(super::extract_instance_pid(json, "cfg01411c"), Some(2994));
        assert_eq!(super::extract_instance_pid(json, "cfg99"), None);
        assert_eq!(super::extract_instance_pid("not json", "cfg01411c"), None);
    }
}
