// Copyright 2025 Nym Technologies SA <contact@nymtech.net>
// SPDX-License-Identifier: GPL-3.0-only

//! OpenWrt dnsmasq DNS backend — restart-free upstream switching.
//!
//! dnsmasq's `resolvfile` is repointed (staged uci, never committed — reboot
//! auto-reverts) at a daemon-managed file in `/tmp/resolv.conf.d/`, which the
//! jailed dnsmasq observes through the init script's directory bind-mount and
//! reloads via inotify on every rename-in. Connecting and disconnecting are
//! then just file writes: no `/etc/init.d/dnsmasq restart` (~3.3s plus a
//! LAN-wide DNS outage) on the connect path. dnsmasq is restarted at most
//! once, at first daemon start, and only if its running config doesn't
//! already point at the managed file.
//!
//! A single daemon-lifetime actor owns the managed file: tunnel resolvers
//! while connected, a 5s-interval mirror of netifd's `resolv.conf.auto`
//! while disconnected (tracks WAN DHCP renewals). Serializing all writers
//! through the actor makes a stale mirror write clobbering tunnel resolvers
//! (a DNS leak) structurally impossible.
//!
//! Local programs on the router resolve via 127.0.0.1: repointing
//! `resolvfile` flips the init script's `localuse` logic to write
//! `/tmp/resolv.conf` as `nameserver 127.0.0.1`, so they ride dnsmasq and
//! its cache. We deliberately do not touch `/etc/resolv.conf`.
//!
//! Escape hatch: a committed `noresolv` (AdGuard Home, https-dns-proxy,
//! stubby — user-owned upstream DNS) makes the init script omit
//! `resolv-file=` entirely, so the repoint can never take. Converge detects
//! this and steps aside (`Scheme::UserManaged`): dnsmasq is left untouched,
//! `set_dns` degrades to a cache flush, and the user's chosen upstreams
//! simply ride the tunnel while connected.

use std::{
    fs, io,
    net::IpAddr,
    path::{Path, PathBuf},
    process::Command,
    sync::OnceLock,
    time::Duration,
};

use tokio::sync::{mpsc, oneshot};

pub type Result<T> = std::result::Result<T, Error>;

/// Prefer IPv4 upstream resolvers when both families are present. IPv6
/// upstreams are only reachable when the exit gateway actually carries IPv6,
/// which cannot be verified from the router; unreachable IPv6 upstreams cause
/// per-lookup timeouts in dnsmasq. AAAA records still resolve fine over IPv4
/// transport, so dropping the IPv6 upstreams loses nothing.
fn prefer_ipv4_upstreams(servers: &[std::net::IpAddr]) -> Vec<std::net::IpAddr> {
    let v4: Vec<std::net::IpAddr> = servers.iter().copied().filter(|ip| ip.is_ipv4()).collect();
    if v4.is_empty() { servers.to_vec() } else { v4 }
}

const OPENWRT_RELEASE: &str = "/etc/openwrt_release";
const BACKUP_MARKER: &str = "/tmp/nym-dns-backup";
const RESOLV_CONF: &str = "/etc/resolv.conf";
const RESOLV_CONF_BACKUP: &str = "/tmp/resolv.conf.nymbackup";

/// The daemon-managed resolv file dnsmasq is repointed at. MUST live inside
/// /tmp/resolv.conf.d/: the dnsmasq init script bind-mounts that directory
/// into the ujail (it mounts dirname(resolvfile)), so a file anywhere else
/// would be invisible to the jailed process. It is always a regular file,
/// never a symlink: dnsmasq's inotify build resolves the watch name once at
/// startup, so symlink swaps stop being observed.
const MANAGED_FILE: &str = "/tmp/resolv.conf.d/nym-resolv.conf";
/// Rename source for atomic updates. Basename must not match MANAGED_FILE's
/// (dnsmasq watches the directory by name; the temp write must not trigger).
const MANAGED_TMP: &str = "/tmp/resolv.conf.d/.nym-resolv.tmp";
/// netifd-owned WAN resolv file, mirrored into MANAGED_FILE while disconnected.
const WAN_RESOLV: &str = "/tmp/resolv.conf.d/resolv.conf.auto";

fn render_resolv_conf(servers: &[IpAddr]) -> String {
    let mut out = String::from("# Generated by nym-vpnd\n");
    for server in servers {
        out.push_str(&format!("nameserver {}\n", server));
    }
    out
}

fn generated_conf_points_at(conf: &str, managed_path: &str) -> bool {
    conf.lines()
        .any(|line| line.trim() == format!("resolv-file={}", managed_path))
}

fn committed_has_managed_path(committed_dhcp: &str) -> bool {
    committed_dhcp.contains("nym-resolv.conf")
}

/// First uci section id of type dnsmasq from `uci -X show dhcp` output.
fn parse_dnsmasq_section(uci_show: &str) -> Option<String> {
    uci_show.lines().find_map(|line| {
        let (key, value) = line.split_once('=')?;
        if value == "dnsmasq" {
            key.strip_prefix("dhcp.").map(str::to_owned)
        } else {
            None
        }
    })
}

/// Minimal extraction of the instance pid from `ubus call service list` output.
/// Deliberately not a JSON parser: the shape is stable procd output and we
/// only need one integer; a serde dependency isn't warranted. The pid procd
/// reports is the ujail wrapper's, which forwards SIGHUP to the jailed
/// dnsmasq. Never read the dnsmasq pidfile instead — it contains the PID as
/// seen inside the jail's own PID namespace (i.e. "1").
fn extract_instance_pid(service_json: &str, section: &str) -> Option<u32> {
    let inst = service_json.find(&format!("\"{}\"", section))?;
    let rest = &service_json[inst..];
    let pid_key = rest.find("\"pid\"")?;
    let after = &rest[pid_key + 5..];
    let digits: String = after
        .chars()
        .skip_while(|c| !c.is_ascii_digit())
        .take_while(|c| c.is_ascii_digit())
        .collect();
    digits.parse().ok()
}

/// System interaction boundary, mockable for tests.
trait Sys: Send + Sync + 'static {
    /// Targeted `uci revert` of a single option. Best-effort: reverting an
    /// option that has no staged delta fails harmlessly.
    fn uci_revert_option(&self, key: &str);
    /// `uci set` — staged only, never committed.
    fn uci_set(&self, key: &str, value: &str) -> Result<()>;
    /// The ONE allowed commit: delete an accidentally-committed resolvfile
    /// option (restores the stock default) and commit dhcp.
    fn repair_committed_resolvfile(&self) -> Result<()>;
    /// Contents of the committed /etc/config/dhcp ("" if unreadable).
    fn committed_dhcp(&self) -> String;
    /// Effective truthiness of the section's `noresolv` option via `uci get`.
    /// Must be read AFTER the targeted reverts so a stale staged delta of our
    /// own (≤1.31 scheme) can't masquerade as user intent.
    fn effective_noresolv(&self, section: &str) -> bool;
    /// First uci section of type dnsmasq, e.g. "cfg01411c".
    fn dnsmasq_section(&self) -> Option<String>;
    /// Contents of the generated /var/etc/dnsmasq.conf.<section>.
    fn generated_conf(&self, section: &str) -> Option<String>;
    fn restart_dnsmasq(&self) -> Result<()>;
    /// `ubus call service list '{"name":"dnsmasq"}'` output.
    fn service_json(&self) -> String;
    /// SIGHUP the ujail wrapper (cache flush only — with polling on, dnsmasq
    /// does NOT re-read resolv files on SIGHUP; reload is carried by inotify.
    /// Side effects: re-reads /etc/hosts and runs the lease script per lease).
    fn send_hup(&self, pid: u32);
}

impl<T: Sys> Sys for std::sync::Arc<T> {
    fn uci_revert_option(&self, key: &str) {
        (**self).uci_revert_option(key)
    }
    fn uci_set(&self, key: &str, value: &str) -> Result<()> {
        (**self).uci_set(key, value)
    }
    fn repair_committed_resolvfile(&self) -> Result<()> {
        (**self).repair_committed_resolvfile()
    }
    fn committed_dhcp(&self) -> String {
        (**self).committed_dhcp()
    }
    fn effective_noresolv(&self, section: &str) -> bool {
        (**self).effective_noresolv(section)
    }
    fn dnsmasq_section(&self) -> Option<String> {
        (**self).dnsmasq_section()
    }
    fn generated_conf(&self, section: &str) -> Option<String> {
        (**self).generated_conf(section)
    }
    fn restart_dnsmasq(&self) -> Result<()> {
        (**self).restart_dnsmasq()
    }
    fn service_json(&self) -> String {
        (**self).service_json()
    }
    fn send_hup(&self, pid: u32) {
        (**self).send_hup(pid)
    }
}

struct RealSys;

impl Sys for RealSys {
    fn uci_revert_option(&self, key: &str) {
        let output = Command::new("uci").args(["revert", key]).output();
        if let Err(e) = output {
            tracing::warn!("uci revert {} failed to execute: {}", key, e);
        }
    }

    fn uci_set(&self, key: &str, value: &str) -> Result<()> {
        uci_set(key, value)
    }

    fn repair_committed_resolvfile(&self) -> Result<()> {
        let run = |args: &[&str]| -> Result<()> {
            let output = Command::new("uci")
                .args(args)
                .output()
                .map_err(|e| Error::UciCommand(e.to_string()))?;
            if !output.status.success() {
                let stderr = String::from_utf8_lossy(&output.stderr);
                return Err(Error::UciCommand(format!("uci {:?} failed: {}", args, stderr)));
            }
            Ok(())
        };
        run(&["delete", "dhcp.@dnsmasq[0].resolvfile"])?;
        run(&["commit", "dhcp"])
    }

    fn committed_dhcp(&self) -> String {
        fs::read_to_string("/etc/config/dhcp").unwrap_or_default()
    }

    fn effective_noresolv(&self, section: &str) -> bool {
        let output = Command::new("uci")
            .args(["get", &format!("dhcp.{}.noresolv", section)])
            .output();
        // Unset option → uci exits non-zero → not noresolv.
        let Ok(output) = output else { return false };
        if !output.status.success() {
            return false;
        }
        // config_get_bool truthy set.
        matches!(
            String::from_utf8_lossy(&output.stdout).trim(),
            "1" | "on" | "true" | "yes" | "enabled"
        )
    }

    fn dnsmasq_section(&self) -> Option<String> {
        // -X: raw section ids (cfg01411c), not extended syntax (@dnsmasq[0]).
        // procd keys its service instances by the raw id.
        let output = Command::new("uci").args(["-X", "show", "dhcp"]).output().ok()?;
        parse_dnsmasq_section(&String::from_utf8_lossy(&output.stdout))
    }

    fn generated_conf(&self, section: &str) -> Option<String> {
        fs::read_to_string(format!("/var/etc/dnsmasq.conf.{}", section)).ok()
    }

    fn restart_dnsmasq(&self) -> Result<()> {
        restart_dnsmasq()
    }

    fn service_json(&self) -> String {
        Command::new("ubus")
            .args(["call", "service", "list", r#"{"name":"dnsmasq"}"#])
            .output()
            .map(|o| String::from_utf8_lossy(&o.stdout).into_owned())
            .unwrap_or_default()
    }

    fn send_hup(&self, pid: u32) {
        // BusyBox kill; avoids a libc dependency for one signal.
        let result = Command::new("kill").args(["-HUP", &pid.to_string()]).output();
        match result {
            Ok(o) if o.status.success() => {}
            Ok(o) => tracing::warn!(
                "kill -HUP {} failed: {}",
                pid,
                String::from_utf8_lossy(&o.stderr)
            ),
            Err(e) => tracing::warn!("kill -HUP {} failed to execute: {}", pid, e),
        }
    }
}

enum ConvergeOutcome {
    /// dnsmasq is running and its generated config points at the managed file.
    Ready,
    /// The repoint is staged but dnsmasq is administratively stopped; we leave
    /// it stopped (it will pick up the staged config whenever it starts).
    DnsmasqStopped,
    /// Committed `noresolv` in the user's dhcp config: the init script never
    /// emits a `resolv-file=` line, so the repoint scheme cannot work — and
    /// the user has deliberately taken ownership of upstream DNS (AdGuard
    /// Home, https-dns-proxy, stubby all commit this). Leave dnsmasq alone;
    /// their upstreams ride the tunnel while connected.
    UserManagedDns,
}

/// Which DNS handover scheme converge settled on, cached for the actor's
/// lifetime (re-checked on connect via the self-heal paths).
#[derive(Clone, Copy, PartialEq)]
enum Scheme {
    /// dnsmasq reads upstreams from our managed resolv file.
    ManagedFile,
    /// User-managed upstreams (committed `noresolv`); we never touch dnsmasq.
    UserManaged,
}

/// Who owns dnsmasq's upstream resolvers right now — i.e. whether the DNS
/// servers configured in nym-vpnd actually reach the system resolver.
///
/// Reported to callers so the UI can stop claiming a custom-DNS setting is in
/// effect when [`UpstreamOwner::User`] means we deliberately stepped aside.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UpstreamOwner {
    /// We manage dnsmasq's upstreams via the managed resolv file; the
    /// configured DNS servers are applied while connected.
    Vpn,
    /// The user manages upstreams (committed `noresolv`): the configured DNS
    /// servers are **not** applied, and dnsmasq's own `server=` forwards are
    /// what resolve — riding the tunnel while connected.
    User,
    /// No dnsmasq under UCI on this host, so the question doesn't apply.
    NotApplicable,
}

/// Read-only view of who owns the upstreams. Deliberately not routed through
/// the actor and deliberately not cached off `Scheme`: this re-reads the
/// effective `noresolv` so a user who has just edited their dhcp config sees
/// the truth rather than whatever converge last settled on. Being read-only,
/// it must never converge, stage uci, or restart anything.
fn upstream_owner<S: Sys>(sys: &S) -> UpstreamOwner {
    match sys.dnsmasq_section() {
        None => UpstreamOwner::NotApplicable,
        Some(section) if sys.effective_noresolv(&section) => UpstreamOwner::User,
        Some(_) => UpstreamOwner::Vpn,
    }
}

/// Who currently owns dnsmasq's upstream resolvers on this host.
pub fn current_upstream_owner() -> UpstreamOwner {
    if !Path::new(OPENWRT_RELEASE).exists() {
        return UpstreamOwner::NotApplicable;
    }
    upstream_owner(&RealSys)
}

/// Idempotently converge system state onto the managed-resolv-file scheme.
/// Safe to run on every daemon start: it only restarts dnsmasq when the
/// running instance's generated config does not already point at the managed
/// file, so a crash-looping daemon cannot turn into a dnsmasq restart storm.
/// This is also the crash-recovery path — there is no separate marker.
fn converge<S: Sys>(sys: &S, managed_file: &str) -> Result<ConvergeOutcome> {
    // Targeted reverts: clears the legacy (≤1.31) staged noresolv/server-list
    // scheme and any stale repoint of our own, without discarding the user's
    // unrelated staged dhcp edits (never `uci revert dhcp` wholesale).
    sys.uci_revert_option("dhcp.@dnsmasq[0].noresolv");
    sys.uci_revert_option("dhcp.@dnsmasq[0].server");
    sys.uci_revert_option("dhcp.@dnsmasq[0].resolvfile");

    // Repair an accidentally-committed repoint (LuCI Save&Apply on the DHCP
    // page commits staged deltas wholesale). Deleting the option restores the
    // stock default; without this, a reboot with the daemon disabled would
    // leave dnsmasq pointing at a file nothing maintains.
    if committed_has_managed_path(&sys.committed_dhcp()) {
        tracing::warn!(
            "Our resolvfile repoint was found committed in /etc/config/dhcp \
             (likely an unrelated dhcp commit); repairing to stock default"
        );
        sys.repair_committed_resolvfile()?;
    }

    let section = sys.dnsmasq_section().ok_or(Error::NoDnsmasq)?;

    // Committed noresolv makes the repoint unreachable (the init script only
    // emits `resolv-file=` when noresolv is unset/false — 24.10 dnsmasq.init
    // gates it), and it signals the user runs their own upstream (DoH proxy,
    // AdGuard Home). Respect it: no repoint, no restarts, connect proceeds
    // with the user's upstreams riding the tunnel.
    if sys.effective_noresolv(&section) {
        tracing::info!(
            "dnsmasq has noresolv set — user manages upstream DNS; \
             leaving it untouched (upstreams ride the tunnel while connected)"
        );
        return Ok(ConvergeOutcome::UserManagedDns);
    }

    for attempt in 0..2u8 {
        sys.uci_set("dhcp.@dnsmasq[0].resolvfile", managed_file)?;

        if extract_instance_pid(&sys.service_json(), &section).is_none() {
            tracing::warn!(
                "dnsmasq is not running; leaving it stopped \
                 (repoint staged for whenever it starts)"
            );
            return Ok(ConvergeOutcome::DnsmasqStopped);
        }

        if sys
            .generated_conf(&section)
            .is_some_and(|conf| generated_conf_points_at(&conf, managed_file))
        {
            return Ok(ConvergeOutcome::Ready);
        }

        sys.restart_dnsmasq()?;

        if sys
            .generated_conf(&section)
            .is_some_and(|conf| generated_conf_points_at(&conf, managed_file))
        {
            return Ok(ConvergeOutcome::Ready);
        }
        // A third-party restart may have raced between our revert and re-stage,
        // regenerating the config from an intermediate state. Retry once.
        tracing::warn!(
            "dnsmasq generated config did not converge after restart (attempt {}), retrying",
            attempt + 1
        );
    }

    Err(Error::DnsmasqRestart(
        "generated config does not point at managed resolv file after restart".into(),
    ))
}

#[derive(thiserror::Error, Debug)]
pub enum Error {
    #[error("not running on OpenWrt")]
    NotOpenWrt,

    #[error("dnsmasq not configured via UCI")]
    NoDnsmasq,

    #[error("failed to execute UCI command: {0}")]
    UciCommand(String),

    #[error("failed to restart dnsmasq: {0}")]
    DnsmasqRestart(String),

    #[error("failed to write {path}: {source}")]
    WriteFile { path: String, source: io::Error },

    #[error("dnsmasq DNS actor is not running")]
    ActorGone,
}

/// How often the actor mirrors `resolv.conf.auto` into the managed file
/// while disconnected. A WAN DHCP renew that changes DNS servers is rare;
/// 5s of staleness is well inside the same failure envelope as the 30s
/// watchdog. Deliberately a poll, not an inotify watch: it folds into the
/// single-owner actor loop as one more `select!` arm.
const MIRROR_INTERVAL: Duration = Duration::from_secs(5);

#[derive(Clone)]
struct Paths {
    managed: PathBuf,
    tmp: PathBuf,
    wan: PathBuf,
}

impl Paths {
    fn real() -> Self {
        Paths {
            managed: MANAGED_FILE.into(),
            tmp: MANAGED_TMP.into(),
            wan: WAN_RESOLV.into(),
        }
    }
}

enum Cmd {
    SetTunnel(Vec<IpAddr>, oneshot::Sender<Result<()>>),
    SetWanMirror(oneshot::Sender<Result<()>>),
}

enum Mode {
    Tunnel,
    WanMirror,
}

/// Atomic update of the managed file: write a temp file in the same tmpfs
/// directory, then rename(2) over the destination. The path is never absent
/// and dnsmasq's inotify sees exactly one IN_MOVED_TO per update. Never
/// truncate-in-place the managed file from anywhere else.
fn write_managed(paths: &Paths, content: &str) -> Result<()> {
    let wrap = |source: io::Error, path: &PathBuf| Error::WriteFile {
        path: path.display().to_string(),
        source,
    };
    fs::write(&paths.tmp, content).map_err(|e| wrap(e, &paths.tmp))?;
    fs::rename(&paths.tmp, &paths.managed).map_err(|e| wrap(e, &paths.managed))
}

/// Current WAN upstreams as file content; header-only if netifd hasn't
/// written `resolv.conf.auto` yet (WAN down at boot — same no-upstream
/// behavior as stock with a missing resolvfile).
fn wan_snapshot(paths: &Paths) -> String {
    fs::read_to_string(&paths.wan).unwrap_or_else(|_| String::from("# Generated by nym-vpnd\n"))
}

/// Best-effort cache flush via SIGHUP to the ubus-reported (ujail wrapper)
/// pid. Cache flush only: on-path answers differ across WAN/tunnel
/// (split-horizon, CDN geo), so flush at transitions; the resolv-file
/// reload itself is carried by dnsmasq's inotify, not by this signal.
fn flush_cache<S: Sys>(sys: &S, section: &str) {
    match extract_instance_pid(&sys.service_json(), section) {
        Some(pid) => sys.send_hup(pid),
        None => tracing::warn!("Could not determine dnsmasq pid; skipping cache flush"),
    }
}

fn ensure_converged<S: Sys>(
    sys: &S,
    paths: &Paths,
    scheme: &mut Option<Scheme>,
) -> Result<Scheme> {
    if let Some(s) = *scheme {
        return Ok(s);
    }
    let s = match converge(sys, &paths.managed.display().to_string())? {
        ConvergeOutcome::UserManagedDns => Scheme::UserManaged,
        ConvergeOutcome::Ready | ConvergeOutcome::DnsmasqStopped => Scheme::ManagedFile,
    };
    *scheme = Some(s);
    Ok(s)
}

fn handle_set_tunnel<S: Sys>(
    sys: &S,
    paths: &Paths,
    scheme: &mut Option<Scheme>,
    servers: &[IpAddr],
) -> Result<()> {
    let s = ensure_converged(sys, paths, scheme)?;
    let servers = prefer_ipv4_upstreams(servers);
    write_managed(paths, &render_resolv_conf(&servers))?;

    if let Some(section) = sys.dnsmasq_section() {
        match s {
            Scheme::ManagedFile => {
                // Self-heal: a third-party dnsmasq restart may have regenerated
                // the config while our staged delta was absent/stale. Cheap
                // re-assert on every connect; full converge (with restart) only
                // on mismatch.
                let managed = paths.managed.display().to_string();
                let pointed = sys
                    .generated_conf(&section)
                    .is_some_and(|conf| generated_conf_points_at(&conf, &managed));
                if !pointed {
                    tracing::warn!(
                        "dnsmasq no longer points at managed resolv file; re-converging"
                    );
                    *scheme = None;
                    ensure_converged(sys, paths, scheme)?;
                }
            }
            Scheme::UserManaged => {
                // Symmetric self-heal: if the user cleared noresolv since we
                // last looked (e.g. uninstalled their DoH proxy), converge onto
                // the managed-file scheme.
                if !sys.effective_noresolv(&section) {
                    tracing::info!("noresolv cleared since last converge; re-converging");
                    *scheme = None;
                    ensure_converged(sys, paths, scheme)?;
                }
            }
        }
        flush_cache(sys, &section);
    }

    // The self-heal above may have switched schemes; log the effective one.
    match scheme.unwrap_or(s) {
        Scheme::ManagedFile => {
            tracing::info!("Configured dnsmasq with VPN DNS servers: {:?}", servers)
        }
        Scheme::UserManaged => tracing::info!(
            "User-managed dnsmasq upstreams (noresolv) left in place; \
             VPN DNS servers not applied: {:?}",
            servers
        ),
    }
    Ok(())
}

fn handle_set_wan<S: Sys>(sys: &S, paths: &Paths) -> Result<()> {
    // No converge requirement: mirroring WAN upstreams into the managed file
    // is correct (and harmless) regardless of repoint state.
    write_managed(paths, &wan_snapshot(paths))?;
    if let Some(section) = sys.dnsmasq_section() {
        flush_cache(sys, &section);
    }
    tracing::info!("Restored dnsmasq to WAN DNS upstreams");
    Ok(())
}

/// Mirror tick: write-if-changed, no cache flush (background tracking of a
/// WAN DHCP renew shouldn't churn LAN client caches).
fn mirror_tick(paths: &Paths) {
    let wan = wan_snapshot(paths);
    let current = fs::read_to_string(&paths.managed).unwrap_or_default();
    if wan != current {
        match write_managed(paths, &wan) {
            Ok(()) => tracing::debug!("Mirrored WAN resolv change into managed resolv file"),
            Err(e) => tracing::warn!("WAN mirror write failed: {}", e),
        }
    }
}

/// Single-writer owner of the managed resolv file for the daemon's lifetime.
/// All mutations (connect, disconnect, mirror ticks) are serialized through
/// this loop; a tick that arrives while in `Mode::Tunnel` is dropped, so the
/// mirror can never clobber tunnel resolvers.
async fn run_actor<S: Sys>(sys: S, paths: Paths, mut rx: mpsc::Receiver<Cmd>) {
    migrate_legacy_state();

    // Seed so dnsmasq never observes a missing file, then converge. A failed
    // converge (e.g. transient uci lock) is retried lazily on first use.
    if let Err(e) = write_managed(&paths, &wan_snapshot(&paths)) {
        tracing::warn!("Failed to seed managed resolv file: {}", e);
    }
    let mut scheme: Option<Scheme> = None;
    if let Err(e) = ensure_converged(&sys, &paths, &mut scheme) {
        tracing::warn!("dnsmasq converge failed (will retry on first use): {}", e);
    }

    let mut mode = Mode::WanMirror;
    let mut tick = tokio::time::interval(MIRROR_INTERVAL);
    tick.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Skip);

    loop {
        tokio::select! {
            cmd = rx.recv() => {
                let Some(cmd) = cmd else { break };
                match cmd {
                    Cmd::SetTunnel(servers, ack) => {
                        let result = handle_set_tunnel(&sys, &paths, &mut scheme, &servers);
                        if result.is_ok() {
                            mode = Mode::Tunnel;
                        }
                        let _ = ack.send(result);
                    }
                    Cmd::SetWanMirror(ack) => {
                        let result = handle_set_wan(&sys, &paths);
                        if result.is_ok() {
                            mode = Mode::WanMirror;
                        }
                        let _ = ack.send(result);
                    }
                }
            }
            _ = tick.tick() => {
                if matches!(mode, Mode::WanMirror) {
                    mirror_tick(&paths);
                }
            }
        }
    }
}

/// One-time migration from the ≤1.31 scheme: if the old crash-recovery
/// artifacts exist (daemon died mid-session before this upgrade), restore
/// /etc/resolv.conf from the old backup and drop the marker. The uci side is
/// covered by converge's targeted reverts. Delete once ≤1.31 is out of the
/// upgrade window.
fn migrate_legacy_state() {
    if Path::new(RESOLV_CONF_BACKUP).exists() {
        tracing::info!("Migrating legacy DNS backup state from pre-1.32");
        if let Ok(backup) = fs::read_to_string(RESOLV_CONF_BACKUP) {
            let _ = fs::write(RESOLV_CONF, backup);
        }
        let _ = fs::remove_file(RESOLV_CONF_BACKUP);
    }
    let _ = fs::remove_file(BACKUP_MARKER);
}

static ACTOR: OnceLock<mpsc::Sender<Cmd>> = OnceLock::new();

/// Eagerly spawn the actor at daemon startup so the one-time converge — and
/// its possible single dnsmasq restart — happens off the connect path. A
/// no-op off OpenWrt or outside a tokio runtime (then the actor spawns
/// lazily on first use instead).
pub fn warm_up() {
    if tokio::runtime::Handle::try_current().is_err() {
        return;
    }
    match Dnsmasq::new() {
        Ok(_) | Err(Error::NotOpenWrt) => {}
        Err(e) => tracing::debug!("dnsmasq warm-up skipped: {}", e),
    }
}

/// Thin client handle; one is created per connect (see linux/mod.rs), all of
/// them talking to the same daemon-lifetime actor.
pub struct Dnsmasq {
    tx: mpsc::Sender<Cmd>,
}

impl Dnsmasq {
    pub fn new() -> Result<Self> {
        // Check if we're on OpenWrt
        if !Path::new(OPENWRT_RELEASE).exists() {
            return Err(Error::NotOpenWrt);
        }

        // Check if dnsmasq is configured via UCI
        let output = Command::new("uci")
            .args(["get", "dhcp.@dnsmasq[0]"])
            .output()
            .map_err(|e| Error::UciCommand(e.to_string()))?;

        if !output.status.success() {
            return Err(Error::NoDnsmasq);
        }

        let tx = ACTOR
            .get_or_init(|| {
                let (tx, rx) = mpsc::channel(8);
                tokio::spawn(run_actor(RealSys, Paths::real(), rx));
                tracing::debug!("OpenWrt dnsmasq DNS actor spawned");
                tx
            })
            .clone();

        Ok(Dnsmasq { tx })
    }

    pub async fn set_dns(&mut self, servers: &[IpAddr]) -> Result<()> {
        let (ack, rx) = oneshot::channel();
        self.tx
            .send(Cmd::SetTunnel(servers.to_vec(), ack))
            .await
            .map_err(|_| Error::ActorGone)?;
        rx.await.map_err(|_| Error::ActorGone)?
    }

    pub async fn reset(&mut self) -> Result<()> {
        let (ack, rx) = oneshot::channel();
        self.tx
            .send(Cmd::SetWanMirror(ack))
            .await
            .map_err(|_| Error::ActorGone)?;
        rx.await.map_err(|_| Error::ActorGone)?
    }
}

/// Run `uci set <key>=<value>` (staged, not committed).
fn uci_set(key: &str, value: &str) -> Result<()> {
    let arg = format!("{}={}", key, value);
    let output = Command::new("uci")
        .args(["set", &arg])
        .output()
        .map_err(|e| Error::UciCommand(e.to_string()))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(Error::UciCommand(format!("uci set {} failed: {}", arg, stderr)));
    }
    Ok(())
}

/// Restart dnsmasq via its init script.
fn restart_dnsmasq() -> Result<()> {
    let output = Command::new("/etc/init.d/dnsmasq")
        .arg("restart")
        .output()
        .map_err(|e| Error::DnsmasqRestart(e.to_string()))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(Error::DnsmasqRestart(stderr.to_string()));
    }
    Ok(())
}

#[cfg(test)]
mod converge_tests {
    use super::*;
    use std::sync::Mutex;

    #[derive(Default)]
    pub(super) struct FakeSys {
        pub calls: Mutex<Vec<String>>,
        pub committed: String,
        pub section: Option<String>,
        // queue of generated-conf reads, popped front on each generated_conf()
        pub generated: Mutex<Vec<Option<String>>>,
        pub running: bool,
        pub noresolv: bool,
    }

    impl Sys for FakeSys {
        fn uci_revert_option(&self, key: &str) {
            self.calls.lock().unwrap().push(format!("revert {key}"));
        }
        fn uci_set(&self, key: &str, value: &str) -> Result<()> {
            self.calls.lock().unwrap().push(format!("set {key}={value}"));
            Ok(())
        }
        fn repair_committed_resolvfile(&self) -> Result<()> {
            self.calls.lock().unwrap().push("repair-commit".into());
            Ok(())
        }
        fn committed_dhcp(&self) -> String {
            self.committed.clone()
        }
        fn effective_noresolv(&self, _section: &str) -> bool {
            self.calls.lock().unwrap().push("get noresolv".into());
            self.noresolv
        }
        fn dnsmasq_section(&self) -> Option<String> {
            self.section.clone()
        }
        fn generated_conf(&self, _section: &str) -> Option<String> {
            let mut q = self.generated.lock().unwrap();
            if q.is_empty() { None } else { q.remove(0) }
        }
        fn restart_dnsmasq(&self) -> Result<()> {
            self.calls.lock().unwrap().push("restart".into());
            Ok(())
        }
        fn service_json(&self) -> String {
            if self.running {
                r#"{"dnsmasq":{"instances":{"cfg01411c":{"running":true,"pid":42}}}}"#.into()
            } else {
                r#"{"dnsmasq":{"instances":{}}}"#.into()
            }
        }
        fn send_hup(&self, pid: u32) {
            self.calls.lock().unwrap().push(format!("hup {pid}"));
        }
    }

    pub(super) fn managed_line() -> String {
        format!("resolv-file={}\n", MANAGED_FILE)
    }

    #[test]
    fn converge_skips_restart_when_already_pointed() {
        let sys = FakeSys {
            section: Some("cfg01411c".into()),
            generated: Mutex::new(vec![Some(managed_line())]),
            running: true,
            ..Default::default()
        };
        let out = converge(&sys, MANAGED_FILE).unwrap();
        assert!(matches!(out, ConvergeOutcome::Ready));
        let calls = sys.calls.lock().unwrap();
        assert!(
            !calls.iter().any(|c| c == "restart"),
            "must not restart when converged: {calls:?}"
        );
        assert!(calls.iter().any(|c| c.starts_with("revert dhcp.@dnsmasq[0].noresolv")));
    }

    #[test]
    fn converge_restarts_once_and_asserts() {
        let sys = FakeSys {
            section: Some("cfg01411c".into()),
            generated: Mutex::new(vec![
                Some("resolv-file=/tmp/resolv.conf.d/resolv.conf.auto\n".into()), // pre-restart read
                Some(managed_line()),                                             // post-restart assert
            ]),
            running: true,
            ..Default::default()
        };
        assert!(matches!(converge(&sys, MANAGED_FILE).unwrap(), ConvergeOutcome::Ready));
        assert_eq!(
            sys.calls.lock().unwrap().iter().filter(|c| *c == "restart").count(),
            1
        );
    }

    #[test]
    fn converge_leaves_stopped_dnsmasq_stopped() {
        let sys = FakeSys {
            section: Some("cfg01411c".into()),
            generated: Mutex::new(vec![None]),
            running: false,
            ..Default::default()
        };
        assert!(matches!(
            converge(&sys, MANAGED_FILE).unwrap(),
            ConvergeOutcome::DnsmasqStopped
        ));
        assert!(!sys.calls.lock().unwrap().iter().any(|c| c == "restart"));
    }

    #[test]
    fn converge_repairs_committed_accident() {
        let sys = FakeSys {
            committed: "option resolvfile '/tmp/resolv.conf.d/nym-resolv.conf'".into(),
            section: Some("cfg01411c".into()),
            generated: Mutex::new(vec![Some(managed_line())]),
            running: true,
            ..Default::default()
        };
        converge(&sys, MANAGED_FILE).unwrap();
        assert!(sys.calls.lock().unwrap().iter().any(|c| c == "repair-commit"));
    }

    #[test]
    fn converge_noresolv_skips_repoint_and_never_restarts() {
        let sys = FakeSys {
            section: Some("cfg01411c".into()),
            running: true,
            noresolv: true,
            ..Default::default()
        };
        let out = converge(&sys, MANAGED_FILE).unwrap();
        assert!(matches!(out, ConvergeOutcome::UserManagedDns));
        let calls = sys.calls.lock().unwrap();
        assert!(
            !calls.iter().any(|c| c == "restart"),
            "noresolv boxes must never be restarted: {calls:?}"
        );
        assert!(
            !calls.iter().any(|c| c.starts_with("set dhcp.@dnsmasq[0].resolvfile")),
            "no repoint may be staged under noresolv: {calls:?}"
        );
    }

    #[test]
    fn converge_reverts_only_targeted_options() {
        let sys = FakeSys {
            section: Some("cfg01411c".into()),
            generated: Mutex::new(vec![Some(managed_line())]),
            running: true,
            ..Default::default()
        };
        converge(&sys, MANAGED_FILE).unwrap();
        let calls = sys.calls.lock().unwrap();
        let reverts: Vec<_> = calls.iter().filter(|c| c.starts_with("revert")).collect();
        assert_eq!(reverts.len(), 3, "exactly noresolv/server/resolvfile: {reverts:?}");
        assert!(
            !calls.iter().any(|c| *c == "revert dhcp"),
            "wholesale revert forbidden"
        );
    }
}

#[cfg(test)]
mod actor_tests {
    use super::converge_tests::FakeSys;
    use super::*;
    use std::sync::{Arc, Mutex};

    async fn spawn_test_actor(with_wan: bool) -> (
        tokio::sync::mpsc::Sender<Cmd>,
        Paths,
        Arc<FakeSys>,
        tempfile::TempDir,
    ) {
        let dir = tempfile::tempdir().unwrap();
        let paths = Paths {
            managed: dir.path().join("nym-resolv.conf"),
            tmp: dir.path().join(".nym-resolv.tmp"),
            wan: dir.path().join("resolv.conf.auto"),
        };
        if with_wan {
            std::fs::write(&paths.wan, "nameserver 203.0.113.1\n").unwrap();
        }
        let generated_line = format!("resolv-file={}\n", paths.managed.display());
        let sys = Arc::new(FakeSys {
            section: Some("cfg01411c".into()),
            generated: Mutex::new(vec![Some(generated_line); 64]),
            running: true,
            ..Default::default()
        });
        let (tx, rx) = tokio::sync::mpsc::channel(8);
        tokio::spawn(run_actor(sys.clone(), paths.clone(), rx));
        (tx, paths, sys, dir)
    }

    #[tokio::test(start_paused = true)]
    async fn set_tunnel_writes_v4_only_and_flushes_cache() {
        let (tx, paths, sys, _dir) = spawn_test_actor(true).await;
        let (ack, rx) = tokio::sync::oneshot::channel();
        tx.send(Cmd::SetTunnel(
            vec!["2620:fe::fe".parse().unwrap(), "10.64.0.1".parse().unwrap()],
            ack,
        ))
        .await
        .unwrap();
        rx.await.unwrap().unwrap();
        let content = std::fs::read_to_string(&paths.managed).unwrap();
        assert!(content.contains("nameserver 10.64.0.1"));
        assert!(!content.contains("2620:fe::fe"));
        assert!(sys.calls.lock().unwrap().iter().any(|c| c.starts_with("hup ")));
    }

    #[tokio::test(start_paused = true)]
    async fn wan_mirror_tracks_while_disconnected_but_never_while_tunnel() {
        let (tx, paths, _sys, _dir) = spawn_test_actor(true).await;
        // connect
        let (ack, rx) = tokio::sync::oneshot::channel();
        tx.send(Cmd::SetTunnel(vec!["10.64.0.1".parse().unwrap()], ack))
            .await
            .unwrap();
        rx.await.unwrap().unwrap();
        // WAN file changes while connected — mirror must NOT clobber tunnel resolvers
        std::fs::write(&paths.wan, "nameserver 192.0.2.53\n").unwrap();
        tokio::time::sleep(std::time::Duration::from_millis(12_000)).await; // > 2 ticks
        assert!(std::fs::read_to_string(&paths.managed).unwrap().contains("10.64.0.1"));
        // disconnect → mirror mode: WAN content must flow in
        let (ack, rx) = tokio::sync::oneshot::channel();
        tx.send(Cmd::SetWanMirror(ack)).await.unwrap();
        rx.await.unwrap().unwrap();
        assert!(std::fs::read_to_string(&paths.managed).unwrap().contains("192.0.2.53"));
        // subsequent WAN change tracked by tick
        std::fs::write(&paths.wan, "nameserver 198.51.100.53\n").unwrap();
        tokio::time::sleep(std::time::Duration::from_millis(12_000)).await;
        assert!(std::fs::read_to_string(&paths.managed).unwrap().contains("198.51.100.53"));
    }

    #[tokio::test(start_paused = true)]
    async fn set_tunnel_succeeds_under_noresolv_without_restart() {
        let dir = tempfile::tempdir().unwrap();
        let paths = Paths {
            managed: dir.path().join("nym-resolv.conf"),
            tmp: dir.path().join(".nym-resolv.tmp"),
            wan: dir.path().join("resolv.conf.auto"),
        };
        let sys = Arc::new(FakeSys {
            section: Some("cfg01411c".into()),
            running: true,
            noresolv: true,
            ..Default::default()
        });
        let (tx, rx) = tokio::sync::mpsc::channel(8);
        tokio::spawn(run_actor(sys.clone(), paths, rx));
        let (ack, arx) = tokio::sync::oneshot::channel();
        tx.send(Cmd::SetTunnel(vec!["10.64.0.1".parse().unwrap()], ack))
            .await
            .unwrap();
        arx.await.unwrap().unwrap(); // connect must NOT fail
        let calls = sys.calls.lock().unwrap();
        assert!(!calls.iter().any(|c| c == "restart"), "no restarts: {calls:?}");
        assert!(
            calls.iter().any(|c| c.starts_with("hup ")),
            "cache still flushed at transition: {calls:?}"
        );
    }

    #[tokio::test(start_paused = true)]
    async fn missing_wan_file_is_tolerated() {
        let (tx, paths, _sys, _dir) = spawn_test_actor(false).await;
        let (ack, rx) = tokio::sync::oneshot::channel();
        tx.send(Cmd::SetWanMirror(ack)).await.unwrap();
        rx.await.unwrap().unwrap(); // must not error
        assert!(paths.managed.exists());
    }

    #[test]
    fn managed_updates_use_rename_not_truncate() {
        let dir = tempfile::tempdir().unwrap();
        let paths = Paths {
            managed: dir.path().join("m"),
            tmp: dir.path().join(".t"),
            wan: dir.path().join("w"),
        };
        write_managed(&paths, "nameserver 10.0.0.1\n").unwrap();
        assert_eq!(
            std::fs::read_to_string(&paths.managed).unwrap(),
            "nameserver 10.0.0.1\n"
        );
        assert!(!paths.tmp.exists(), "temp file must not linger after rename");
    }
}

#[cfg(test)]
mod tests {
    use super::converge_tests::FakeSys;
    use super::prefer_ipv4_upstreams;
    use std::net::IpAddr;

    #[test]
    fn prefers_ipv4_upstreams_when_mixed() {
        let servers: Vec<IpAddr> = vec![
            "2620:fe::fe".parse().unwrap(),
            "9.9.9.9".parse().unwrap(),
            "2606:4700:4700::1111".parse().unwrap(),
            "1.1.1.1".parse().unwrap(),
        ];
        let got = prefer_ipv4_upstreams(&servers);
        assert_eq!(
            got,
            vec!["9.9.9.9".parse::<IpAddr>().unwrap(), "1.1.1.1".parse().unwrap()]
        );
    }

    #[test]
    fn keeps_ipv6_when_no_ipv4_available() {
        let servers: Vec<IpAddr> = vec!["2620:fe::fe".parse().unwrap()];
        assert_eq!(prefer_ipv4_upstreams(&servers), servers);
    }

    #[test]
    fn renders_resolv_conf() {
        let servers: Vec<IpAddr> = vec!["10.0.0.1".parse().unwrap(), "10.0.0.2".parse().unwrap()];
        assert_eq!(
            super::render_resolv_conf(&servers),
            "# Generated by nym-vpnd\nnameserver 10.0.0.1\nnameserver 10.0.0.2\n"
        );
    }

    #[test]
    fn detects_managed_resolv_file_in_generated_conf() {
        let conf = "server=1.1.1.1\nresolv-file=/tmp/resolv.conf.d/nym-resolv.conf\ncache-size=1000\n";
        assert!(super::generated_conf_points_at(conf, super::MANAGED_FILE));
        let stock = "resolv-file=/tmp/resolv.conf.d/resolv.conf.auto\n";
        assert!(!super::generated_conf_points_at(stock, super::MANAGED_FILE));
        // substring must not fool it
        let tricky = "# resolv-file=/tmp/resolv.conf.d/nym-resolv.conf.bak\n";
        assert!(!super::generated_conf_points_at(tricky, super::MANAGED_FILE));
    }

    #[test]
    fn detects_accidentally_committed_repoint() {
        let dirty = "config dnsmasq\n\toption resolvfile '/tmp/resolv.conf.d/nym-resolv.conf'\n";
        assert!(super::committed_has_managed_path(dirty));
        let clean = "config dnsmasq\n\toption resolvfile '/tmp/resolv.conf.d/resolv.conf.auto'\n";
        assert!(!super::committed_has_managed_path(clean));
    }

    #[test]
    fn parses_dnsmasq_section_from_raw_uci_show() {
        // `uci -X show dhcp` emits raw ids; the extended default (@dnsmasq[0])
        // would not match procd's instance key.
        let show = "dhcp.cfg01411c=dnsmasq\ndhcp.cfg01411c.domainneeded='1'\ndhcp.lan=dhcp\n";
        assert_eq!(super::parse_dnsmasq_section(show), Some("cfg01411c".into()));
        assert_eq!(super::parse_dnsmasq_section("dhcp.lan=dhcp\n"), None);
    }

    #[test]
    fn extracts_ujail_wrapper_pid_from_ubus_json() {
        let json = r#"{ "dnsmasq": { "instances": { "cfg01411c": { "running": true, "pid": 2994, "command": ["x"] } } } }"#;
        assert_eq!(super::extract_instance_pid(json, "cfg01411c"), Some(2994));
        assert_eq!(super::extract_instance_pid(json, "cfg99"), None);
        assert_eq!(super::extract_instance_pid("not json", "cfg01411c"), None);
    }

    #[test]
    fn reports_user_ownership_under_noresolv() {
        let sys = FakeSys {
            section: Some("cfg01411c".into()),
            noresolv: true,
            ..Default::default()
        };
        assert_eq!(super::upstream_owner(&sys), super::UpstreamOwner::User);
    }

    #[test]
    fn reports_vpn_ownership_without_noresolv() {
        let sys = FakeSys {
            section: Some("cfg01411c".into()),
            noresolv: false,
            ..Default::default()
        };
        assert_eq!(super::upstream_owner(&sys), super::UpstreamOwner::Vpn);
    }

    #[test]
    fn reports_not_applicable_without_dnsmasq() {
        let sys = FakeSys {
            section: None,
            noresolv: true,
            ..Default::default()
        };
        assert_eq!(
            super::upstream_owner(&sys),
            super::UpstreamOwner::NotApplicable
        );
    }

    /// The query is a status read on a live system; converging or restarting
    /// dnsmasq from a `dns get` would be a nasty surprise.
    #[test]
    fn ownership_query_never_mutates_system_state() {
        let sys = FakeSys {
            section: Some("cfg01411c".into()),
            noresolv: true,
            ..Default::default()
        };
        super::upstream_owner(&sys);
        let calls = sys.calls.lock().unwrap().clone();
        assert_eq!(
            calls,
            vec!["get noresolv".to_string()],
            "status query must only read noresolv: {calls:?}"
        );
    }
}
