[package]
name = "nym-dns"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "lib", "staticlib"]

[lints]
workspace = true

[dependencies]
nix = { workspace = true, features = ["net"] }
thiserror.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = [
    "macros",
    "process",
    "sync",
    "io-util",
    "rt",
    "time",
] }
futures.workspace = true
triggered.workspace = true

nym-routing.workspace = true
nym-dbus.workspace = true
nym-common.workspace = true

which.workspace = true
inotify.workspace = true
resolv-conf.workspace = true
duct.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "test-util"] }
tempfile.workspace = true
