[package]
name = "nym-firewall"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
ipnetwork.workspace = true
libc.workspace = true
thiserror.workspace = true
tracing.workspace = true

nym-dns.workspace = true
nym-firewall-config.workspace = true

nix = { workspace = true, features = ["net", "fs"] }
