[package]
name = "nym-offline-monitor"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
thiserror.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = ["macros", "sync", "time", "rt"] }
tokio-util.workspace = true

async-trait.workspace = true

nym-common.workspace = true
nym-routing.workspace = true
