[package]
name = "nym-routing"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
thiserror.workspace = true
futures.workspace = true
ipnetwork.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = [
    "process",
    "rt-multi-thread",
    "net",
    "io-util",
    "time",
    "sync",
    "macros",
] }
nym-common.workspace = true
libc.workspace = true
netlink-packet-route = { workspace = true, features = ["rich_nlas"] }
netlink-packet-core.workspace = true
netlink-sys.workspace = true
rtnetlink.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
