#!/bin/sh /etc/rc.common
START=90
STOP=10
USE_PROCD=1

start_service() {
    mkdir -p /var/lib/nym-vpn
    procd_open_instance
    procd_set_param command /usr/sbin/nym-vpnd
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param pidfile /var/run/nym-vpnd.pid
    procd_close_instance
}

stop_service() {
    /usr/bin/nym-vpnc disconnect 2>/dev/null || true
}
